

<?php

/**
 * @file
 * Contains ighn_core.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Drupal\media\Entity\Media;
use Drupal\file\Entity\File;
use Drupal\views\Views;

/**
 * Implements hook_module_implements_alter().
 */
function ighn_core_module_implements_alter(&$implementations, $hook) {
  $hooks_to_order = [
    'form_alter',
  ];

  if (in_array($hook, $hooks_to_order)) {
    $group = $implementations['ighn_core'];
    unset($implementations['ighn_core']);
    $implementations['ighn_core'] = $group;
  }
}

/**
 * Implements hook_theme().
 */
function ighn_core_theme($existing, $type, $theme, $path) {
    return [
      'node__ighn_person__default' => [
        'template' => 'node--ighn-person--full',
        'base hook' => 'node',
      ],
    ];
  }