

<?php

/**
 * @file
 * Contains ighn_core.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_page_attachments().
 */
function ighn_core_page_attachments(array &$attachments) {
  // Attach css file on admin pages.
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $attachments['#attached']['library'][] = 'ighn_core/ighn-overrides';
  }
}

/**
 * Implements hook_theme for IGHN Person CT and IGHN Person View().
 */
function ighn_core_theme($existing, $type, $theme, $path) {
  return [
    'node__ighn_person__teaser' => [
      'template' => 'node--ighn-person--teaser',
      'base hook' => 'node',
    ],
    'node__ighn_person__full' => [
      'template' => 'node--ighn-person--full',
      'base hook' => 'node',
    ],
    'views_view_unformatted__ighn_person_view' => [
        'template' => 'views-view-unformatted--ighn-person-view',
        'base hook' => 'views',
    ],
    'field__comma_separated' => [
      'template' => 'field--comma-separated',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function ighn_core_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  switch ($variables["element"]["#field_name"]) {
    case 'field_ighn_person_focus_areas':
    case 'field_ighn_person_global_regions':
    case 'field_ighn_person_language':
//      if ($variables["element"]["#formatter"] == 'entity_reference_label') {
      $suggestions[] = 'field__comma_separated';
//      }
      break;
  }
}

/**
 * Implements hook_entity_presave().
 */
function ighn_core_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'ighn_person':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_ighn_person_first_name')->value . " " . $entity->get('field_ighn_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}
