<?php

/**
 * @file
 * Contains the sitenow_student_profile module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function studentlife_topics_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'studentlife_topics/topics';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function studentlife_topics_preprocess_layout(&$variables) {
  /** @var \Drupal\Core\Layout\LayoutDefinition $layout */
  $layout = $variables['layout'];

  // Process the header layout.
  if ($layout->id() === 'layout_header') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $node = (isset($node) ? $node : \Drupal::routeMatch()->getParameter('node_preview'));
    if ($node instanceof NodeInterface) {
      if (in_array($node->getType(), [
        'topic_landing_page',
      ])) {
        if (!isset($variables['banner_attributes'])) {
          $variables['banner_settings'] = [];
        }
      }

      switch ($node->getType()) {
        case 'topic_landing_page':
          if ($node->hasField('field_image') && !$node->get('field_image')->isEmpty()) {
            // Set the featured image display.
            $variables['featured_image_display'] = 'medium';
            // Set banner defaults.
            $variables['banner_settings']['horizontal_align'] = 'center';
            $variables['banner_settings']['vertical_align'] = 'center';
          }
          break;
      }
    }
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function studentlife_topics_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  switch ($variables["element"]["#field_name"]) {
    case 'field_topic_landing_page_tags':
      $suggestions[] = 'field__comma_separated';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function studentlife_topics_theme($existing, $type, $theme, $path) {
  return [
    'field__node__title__topic_landing_page__default' => [
      'template' => 'field--node--title--topic-landing-page--default',
      'base hook' => 'field',
    ],
    'node__topic_landing_page__teaser' => [
      'template' => 'node--topic-landing-page--teaser',
      'base hook' => 'node',
    ],
  ];
}
