<?php

/**
 * @file
 * Contains the sitenow_student_profile module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_form_alter().
 */
function studentlife_topics_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_topic_collection_form':
    case 'node_topic_collection_edit_form':
      // Set form defaults if they exist.
      _sitenow_node_form_defaults($form, $form_state);
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function studentlife_topics_preprocess_html(&$variables) {
  $variables['#attached']['library'][] = 'studentlife_topics/topics';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function studentlife_topics_preprocess_layout(&$variables) {
  /** @var \Drupal\Core\Layout\LayoutDefinition $layout */
  $layout = $variables['layout'];

  // Process the header layout.
  if ($layout->id() === 'layout_header') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $node = ($node ?? \Drupal::routeMatch()->getParameter('node_preview'));
    if ($node instanceof NodeInterface) {
      if (in_array($node->getType(), [
        'topic_collection',
      ])) {
        if (!isset($variables['banner_attributes'])) {
          $variables['banner_settings'] = [];
        }
      }

      switch ($node->getType()) {
        case 'topic_collection':
          if ($node->hasField('field_image') && !$node->get('field_image')->isEmpty()) {
            // Set the featured image display.
            $variables['featured_image_display'] = 'medium';
            // Set banner defaults.
            $variables['banner_settings']['horizontal_align'] = 'center';
            $variables['banner_settings']['vertical_align'] = 'center';
          }
          else {
            $variables['attributes']['class'][] = 'bg--gray';
          }
          break;
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function studentlife_topics_theme($existing, $type, $theme, $path) {
  return [
    'node__topic_collection__teaser' => [
      'template' => 'node--topic-collection--teaser',
      'base hook' => 'node',
    ],
  ];
}
