project:
  machine_name: org-uihealthcareebp
  human_name: ebp.uihealthcare.org
  local:
    hostname: org-uihealthcareebp.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: org-uihealthcareebp.prod
drupal:
  db:
    database: ebp_uihealthcare_org
uiowa:
  requester: dholterh
  site-name: 'Evidence-Based Practice'
