project:
  machine_name: sitesdaniela-coelho
  human_name: daniela-coelho.sites.uiowa.edu
  local:
    hostname: sitesdaniela-coelho.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: sitesdaniela-coelho.prod
drupal:
  db:
    database: daniela_coelho_sites_uiowa_edu
uiowa:
  requester: coelho
  site-name: daniela-coelho
