<?php

/**
 * @file
 * Provides a basic event content type for standard sites.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function entity_types_person_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.entity_types_person':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }

      /** @var \Drupal\Core\Extension\ModuleHandler $moduleHandler */
      $moduleHandler = \Drupal::service('module_handler');
      if ($moduleHandler->moduleExists('markdown')) {
        $filters = $moduleHandler->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function entity_types_person_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'entity_types_person/entity_types_person_styling';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function entity_types_person_form_node_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  // Get the node entity from the form.
  $entity = $form_state->getFormObject()->getEntity();

  // Hide the node title and set default stub.
  if ($entity->bundle() == 'person') {
    $form['title']['#type'] = 'hidden';
    $form['title']['widget'][0]['value']['#default_value'] = 'DEFAULT NAME';
    $form['title']['widget'][0]['value']['#attributes']['disabled'] = TRUE;
  }
}

/**
 * Implements hook_entity_presave().
 */
function entity_types_person_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'person':
      // Setting the title with the value of output.
      $output = '';
      $output .= $entity->get('person_first_name')->value;
      if (!empty($entity->get('person_middle_name')->value)) {
        $output .= " " . substr($entity->get('person_middle_name')->value, 0, 1);
      }
      else {
        $output .= " ";
      }
      $output .= " " . $entity->get('person_last_name')->value;
      if (!empty($entity->get('person_suffix')->value)) {
        $output .= ", " . $entity->get('person_suffix')->value;
      }
      if (!empty($entity->get('person_credentials')->value)) {
        $output .= ", " . $entity->get('person_credentials')->value;
      }
      $entity->setTitle($output);
      break;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function entity_types_person_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'people') {
    $unique_nids = [];
    $new_result = [];

    // Display only one result in views, do not display duplicates.
    foreach ($view->result as $row) {
      if (!in_array($row->nid, $unique_nids)) {
        $new_result[] = $row;
        $unique_nids[] = $row->nid;
      }
    }

    $view->result = $new_result;
  }

  /* Hide the exposed filter is the view is empty */
  if ($view->id() == 'people') {
    if (empty($view->result) && empty($view->getExposedInput())) {
      $view->exposed_widgets = NULL;
    }
  }
}
