<?php

/**
 * @file
 * Contains lb_enhancements.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\layout_builder_custom\LayoutBuilderPreRender;
use Drupal\layout_builder_styles\LayoutBuilderStyleGroups;

/**
 * Implementation of hook_element_info_alter().
 *
 * This doesn't work because it is for changing broad-level definitions for how elements
 * are handled. It doesn't allow for setting the configuration for an individual element.
 *
 * @param array $types
 *   The types to be altered.
 */
function layout_builder_custom_element_info_alter(array &$types) {
  $types['layout_builder']['#pre_render'][] = LayoutBuilderPreRender::class . '::preRender';
}

/**
 * Implements hook_form_alter().
 */
function layout_builder_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'layout_builder_add_block':
    case 'layout_builder_update_block':

      /** @var \Drupal\layout_builder\SectionComponent $component */
      $component = $form_state->getFormObject()->getCurrentComponent();
      $block = $component->getPlugin();

      // Add custom validation for certain blocks/regions to validate.
      $form['#validate'][] = '_layout_builder_custom_block_validate';

      // Add custom process callback for certain blocks to alter form elements.
      $form['settings']['block_form']['#process'][] = '_layout_builder_custom_process_element';

      // Override display of layout builder styles.
      $styles_exist = FALSE;
      $styles_enabled = FALSE;

      // Loop through layout builder style groups.
      $groups = LayoutBuilderStyleGroups::getGroups();

      foreach (array_keys($groups) as $group) {
        $lbs = 'layout_builder_style_' . $group;

        if (isset($form[$lbs])) {
          $styles_exist = TRUE;

          if ($form_id == 'layout_builder_update_block') {
            // Set enabled flag based on whether a default value exists
            // for this layout builder style.
            $styles_enabled = !empty($form[$lbs]['#default_value']);
          }

          // Set a state for the layout builder style to toggle
          // based on the value of the override value specified below.
          $form[$lbs]['#states'] = [
            'visible' => [
              ':input[name="layout_builder_block_override"]' => [
                'checked' => TRUE,
              ],
            ],
          ];

          // Make the background option single select only.
          if ($group === 'background') {
            $form[$lbs]['#multiple'] = FALSE;
          }
        }
      }

      // Add a checkbox to toggle whether the styles should show.
      if ($styles_exist) {
        $form['layout_builder_block_override'] = [
          '#type' => 'checkbox',
          '#title' => t('Override style options'),
          '#required' => FALSE,
          '#default_value' => $styles_enabled,
          '#weight' => 80,
        ];
      }

      // Always set title field to not be required.
      $form['settings']['label']['#required'] = FALSE;

      unset($form['settings']['label']);
      unset($form['settings']['label_display']);
      unset($form['settings']['admin_label']['#title']);

      if ($block->getPluginId() == 'menu_block:main') {
        /** @var \Drupal\Core\Plugin\DefaultPluginManager $filters */
        $filters = \Drupal::service('plugin.manager.config_filter')->getDefinitions();
        $collegiate_split = 'config_split:collegiate';
        // 'collegiate' split either doesn't exist or isn't enabled.
        if (!isset($filters[$collegiate_split]) || !$filters[$collegiate_split]['status']) {
          // Restrict block settings on main navigation block.
          $form["settings"]["menu_levels"]['#access'] = FALSE;
          $form["settings"]["advanced"]['#access'] = FALSE;
          $form["settings"]["style"]['#access'] = FALSE;
        }

        // Set defaults.
        $form["settings"]["menu_levels"]["level"]["#default_value"] = 2;
        $form["settings"]["advanced"]["follow"]["#default_value"] = 1;
      }

      $form['settings'] += [
        '#weight' => 0,
      ];

      // Change collection view_mode field to radios and remove the 'default' option.
      if (isset($form['settings']['block_form']['#block'])
      && $form['settings']['block_form']['#block']->bundle() === 'uiowa_collection') {
        $form['settings']['view_mode']['#type'] = 'radios';
        array_shift($form['settings']['view_mode']['#options']);

        // @todo Re-enable 'tab' after theming/functionality is in place.
        unset($form['settings']['view_mode']['#options']['tab']);

        $view_options = [
          'accordion',
          'descriptive_list',
          'tab',
        ];

        // If view mode not in our options (eg 'full'), set it to <dl>.
        if (!in_array($form['settings']['view_mode']['#default_value'], $view_options)) {
          $form['settings']['view_mode']['#default_value'] = 'descriptive_list';
        }
      }

      break;

    case 'layout_builder_configure_section':
      $single_select_groups = [
        'layout_builder_style_background',
        'layout_builder_style_container',
      ];

      foreach ($single_select_groups as $group) {
        if (isset($form[$group])) {
          // Disable multiple selection and weight to the top so focus on a
          // Chosen-enabled select does not obscure other form elements.
          $form[$group]['#multiple'] = FALSE;
          $form[$group]['#weight'] = 0;
        }
      }

      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function layout_builder_custom_form_node_page_layout_builder_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'layout_builder_custom/layout_builder_custom.overrides';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function layout_builder_custom_form_node_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set default node.body text format to filtered over minimal.
  $form['body']['widget'][0]['#format'] = 'filtered_html';
}

/**
 * Custom validation for layout_builder_add/update_block form.
 *
 * @param array $form
 *   The form element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function _layout_builder_custom_block_validate(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\layout_builder\Section $section */
  $section = $form_state->getFormObject()->getCurrentSection();

  /** @var \Drupal\layout_builder\SectionComponent $component */
  $component = $form_state->getFormObject()->getCurrentComponent();
  $block = $component->getPlugin();

  // Require horizontal style if this card is in a one column layout.
  if ($section->getLayoutId() == 'layout_onecol' && $block->getPluginId() == 'inline_block:uiowa_card') {
    $styles = $form_state->getValue('layout_builder_style_default');

    if (!isset($styles['block_card_style_horizontal'])) {
      $form_state->setErrorByName('layout_builder_block_override', t('Cards rendered within a one column layout must have the horizontal style.'));
    }
  }

  // Add a character limit to the stat block prefix/suffix fields.
  if ($block->getPluginId() == 'inline_block:uiowa_statistic') {
    $block_form = $form_state->getValue('settings')['block_form'];
    $prefix = $block_form['field_uiowa_statistic_title_pre'][0]['value'];
    $suffix = $block_form['field_uiowa_statistic_title_suf'][0]['value'];
    if (strlen($prefix) > 3) {
      $form_state->setErrorByName('settings][block_form][field_uiowa_statistic_title_pre', t('Prefix cannot exceed 3 characters.'));
    }
    if (strlen($suffix) > 3) {
      $form_state->setErrorByName('settings][block_form][field_uiowa_statistic_title_suf', t('Suffix cannot exceed 3 characters.'));
    }
  }
}

/**
 * Custom process block form elements.
 *
 * @param array $element
 *   The current block element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current form state.
 *
 * @return array
 *   The processed block element.
 */
function _layout_builder_custom_process_element(array $element, FormStateInterface $form_state) {
  /** @var \Drupal\layout_builder\SectionComponent $component */
  $component = $form_state->getFormObject()->getCurrentComponent();
  $block = $component->getPlugin();

  switch ($block->getPluginId()) {
    case 'inline_block:uiowa_text_area':
      // Set the default text format to filtered.
      if (isset($element['field_uiowa_text_area'])) {
        $element['field_uiowa_text_area']['widget'][0]['#format'] = 'filtered_html';
      }

      if (isset($element['field_uiowa_headline'])) {
        // Unset the unnecessary 'child_heading_size' field option.
        unset($element['field_uiowa_headline']['widget'][0]['container']['child_heading_size']);
        // Update the help text.
        $element['field_uiowa_headline']['widget'][0]['container']['heading_size']['#description'] =
          t('The heading size for the block title.');
        // Add in the 'h6' option.
        $element['field_uiowa_headline']['widget'][0]['container']['heading_size']['#options']['h6'] = 'Heading 6';
      }
      break;

    case 'inline_block:uiowa_articles':
    case 'inline_block:uiowa_people':
    case 'inline_block:uiowa_events':
      if (isset($element["field_collection_more_path"])) {
        $element["field_collection_more_path"]['#states'] = [
          'visible' => [
            ':input[name="settings[block_form][field_collection_more][value]"]' => [
              'checked' => TRUE,
            ],
          ],
        ];
      }
      break;

    case 'inline_block:uiowa_image_gallery':
      if (isset($element['field_uiowa_headline'])) {
        // Unset the unnecessary 'child_heading_size' field option.
        unset($element['field_uiowa_headline']['widget'][0]['container']['child_heading_size']);
        // Update the help text.
        $element['field_uiowa_headline']['widget'][0]['container']['heading_size']['#description'] =
          t('The heading size for the block title.');
        // Add in the 'h6' option.
        $element['field_uiowa_headline']['widget'][0]['container']['heading_size']['#options']['h6'] = 'Heading 6';
      }
      break;

    case 'inline_block:uiowa_collection':
      if (isset($element['field_uiowa_headline'])) {
        // Update the help text.
        $element['field_uiowa_headline']['widget'][0]['container']['heading_size']['#description'] =
          t('The heading size for the block title. Accordion item headings will be set one heading level lower. Does not apply to descriptive list.');
        $element['field_uiowa_headline']['widget'][0]['container']['child_heading_size']['#description'] =
          t('The heading size for all accordion headings. Does not apply to descriptive list.');
      }
      break;

  }
  return $element;
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function layout_builder_custom_field_widget_paragraphs_form_alter(array &$element, FormStateInterface &$form_state, array $context) {
  if (isset($element['#paragraph_type'])) {
    switch ($element['#paragraph_type']) {

      case 'uiowa_collection_item':
      case 'uiowa_slide':
        // Pop the headline and place it in the label.
        $headline = array_shift($element['top']['summary']['fields_info']['#summary']['content']);
        $element['top']['type']['label']['#markup'] = $headline;
        break;

    }
  }
}

/**
 * Implements hook_theme().
 */
function layout_builder_custom_theme($existing, $type, $theme, $path) {
  $theme = [
    'uiowa_headline_widget' => [
      'variables' => [
        'headline' => NULL,
        'heading_size' => NULL,
        'hide_headline' => NULL,
        'child_heading_size' => NULL,
      ],
    ],
  ];
  return $theme;
}
