<?php

/**
 * @file
 * Contains ccom_core.module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;
use Drupal\ctools_views\Plugin\Display\Block;
use Drupal\layout_builder\Form\ConfigureBlockFormBase;
use Drupal\layout_builder_custom\LayoutBuilderPreRender;
use Drupal\layout_builder_custom\LayoutBuilderStylesHelper;
use Drupal\layout_builder_custom\Plugin\Display\ListBlock;
use Drupal\layout_builder_styles\LayoutBuilderStyleInterface;
use Drupal\uiowa_core\Element\Card;
use Drupal\uiowa_core\HeadlineHelper;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_ccom_preprocess_block(&$variables) {
  if (isset($variables['attributes']['id']) && $variables['attributes']['id'] ==='block-uids-base-footercontactinfo') {
    $current_path = \Drupal::request()->getRequestUri();
    $full_url = $_SERVER["HTTP_HOST"] .$current_path;
    $newlink = '<p><a href="http://hc-vbugtracker.healthcare.uiowa.edu/projects/uihc-org/issues/new?issue[custom_field_values][1]=' . $full_url . '">Report an issue with this page</a></p>';
    $variables["content"]["field_uiowa_text_area"][0]["#text"] .= $newlink;

  }
}
