<?php

/**
 * @file
 * Install, update and uninstall functions for the Admissions Core module.
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Config\FileStorage;

/**
 * Implements hook_install().
 */
function admissions_core_install() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

/**
 * Implements hook_uninstall().
 */
function admissions_core_uninstall() {
  \Drupal::messenger()->addStatus(__FUNCTION__);
}

