<?php

/**
 * @file
 * Primary module hooks for Admissions Core module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\node\Entity\Node;
use Drupal\views\ViewExecutable;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme for Scholarship teaser.
 */
function admissions_core_theme($existing, $type, $theme, $path) {
  return [
    'node__scholarship__teaser' => [
      'template' => 'node--scholarship--teaser',
      'base hook' => 'node',
    ],
    'views_view_unformatted__scholarships__block_scholarships' => [
      'template' => 'views-view-unformatted--scholarships--block-scholarships',
      'base hook' => 'view',
    ],
    'views_view_unformatted__counselors' => [
      'template' => 'views-view-unformatted--counselors',
      'base hook' => 'view',
    ],
    'views_view_unformatted__student_profiles' => [
      'template' => 'views-view-unformatted--student-profiles',
      'base hook' => 'view',
    ],
    'views_view_unformatted__person_card' => [
      'template' => 'views-view-unformatted--person-card',
      'base hook' => 'view',
    ],
    'node__view__counselors' => [
      'template' => 'node--view--counselors',
      'base hook' => 'node',
    ],
    'node__view__student_profiles' => [
      'template' => 'node--view--student-profiles',
      'base hook' => 'node',
    ],
    'field__comma_separated' => [
      'template' => 'field--comma-separated',
      'base hook' => 'field',
    ],
    'field__field_student_profile_blurb' => [
      'template' => 'field--field-student-profile-blurb',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function admissions_core_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  switch ($variables["element"]["#field_name"]) {
    case 'field_person_territory':
      $suggestions[] = 'field__comma_separated';
      break;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function admissions_core_views_pre_render(ViewExecutable $view) {
  if ($view->id() == "counselors") {
    switch ($view->current_display) {
      case 'block_counselors':
      case 'page_counselors':
        $view->element['#attached']['library'][] = 'admissions_core/counselors-list';
        $view->element['#attached']['library'][] = 'admissions_core/person';
        break;

    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function admissions_core_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'student_profile':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . " " . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function admissions_core_preprocess_field(&$variables) {
  $element = $variables['element'];
  $node = $element['#object'];

  switch ($variables["element"]["#field_name"]) {
    case 'field_person_hometown':
      if ($node->hasField('field_person_hometown') && !$node->get('field_person_hometown')->isEmpty()) {
        $variables["label"]= array(
          '#type' => 'markup',
          '#markup' => '<i class="fa fa-map-marker-alt" aria-hidden="true"></i>',
          );
        $hometown = $node->hasField('field_person_hometown') ? $node->field_person_hometown->value : NULL;
        $country = $node->hasField('field_student_profile_country') ? $node->field_student_profile_country->value : NULL;
        if ($hometown && $country) {
          if ($country === 'US') {
            $state = $node->hasField('field_person_territory') ? $node->field_person_territory->value : NULL;
            if ($state) {
              $hometown .= ", $state";
            }
          }
          else {
            $country_value = \Drupal::service('country_manager')->getList()[$country]->__toString();
            $hometown .= ", $country_value";
          }
        }
        $variables['items'][0]['content']['#context']['value'] = $hometown;
      }
      break;
    case 'field_student_profile_major':
      if ($node->hasField('field_student_profile_major') && !$node->get('field_student_profile_major')->isEmpty()) {
        $variables["label"]= array(
          '#type' => 'markup',
          '#markup' => '<i class="fas fa-book" aria-hidden="true"></i>',
          );
      }
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function admissions_core_preprocess_node(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $node = $variables["node"];
    switch ($node->getType()) {
      case 'person':
        $variables['#attached']['library'][] = 'admissions_core/person';
        break;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @param \Drupal\node\Entity\Node $node
 *   Get straight to the node instead of through entity.
 */
function admissions_core_node_presave(Node $node) {
  // Used on Admissions counselors map.
  if ($node->getType() == 'person') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 *
 * @param \Drupal\node\Entity\Node $node
 *   Get straight to the node instead of through entity.
 */
function admissions_core_node_delete(Node $node) {
  // Used on Admissions counselors map.
  if ($node->getType() == 'person') {
    $tags = ['node_type:' . $node->getType()];
    Cache::invalidateTags($tags);
  }
}

function admissions_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-counselors-block-counselors') {
    $form["territory"]["#options"]["All"] = t("- All -");
  }
}
