_core:
  default_config_hash: FHr6psQnRtYvXa9wwVyQsT3ytUtv2w9OvbvbdMDq4a0
langcode: en
consentModal:
  title: 'Privacy notice'
  description: 'This website stores cookies on your device to enhance site navigation, analyze site usage, and assist in our marketing efforts. Read our {privacyPolicy} for more information.'
  privacyPolicy:
    name: 'privacy policy'
    text: 'Read our {privacyPolicy} for more information.'
    url: 'https://uiowa.edu/privacy'
consentNotice:
  title: 'Privacy notice'
  changeDescription: 'There were changes since your last visit, please update your consent.'
  description: 'This website stores cookies on your device to enhance site navigation, analyze site usage, and assist in our marketing efforts. Read our {privacyPolicy} for more information.'
  learnMore: Customize
ok: Okay
save: Save
decline: Decline
close: Close
acceptAll: 'Accept all'
acceptSelected: 'Accept selected'
service:
  disableAll:
    title: 'Toggle all services'
    description: 'Use this switch to enable/disable all services.'
  optOut:
    title: (opt-out)
    description: 'This service is loaded by default (opt-out possible).'
  required:
    title: '(always required)'
    description: 'This service is always required.'
  purposes: Purposes
  purpose: Purpose
contextualConsent:
  acceptAlways: Always
  acceptOnce: 'Yes (this time)'
  description: 'Load external content supplied by {title}?'
poweredBy: 'Powered by Klaro!'
