# Configuration for drush-cron-*.log
/shared/logs/drush-cron-*.log {
  rotate 3
  weekly
  missingok
  compress
  notifempty
  dateext
  dateformat -%Y-%m-%d.log
}

# Configuration for parallel_deploy_log files
/shared/logs/parallel_deploy.log {
  rotate 3
  daily
  missingok
  nocompress
  nocreate
  notifempty
  copytruncate
}
