<?php

/**
 * @file
 * Primary module hooks for Uiowa Core module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;

/**
 * Implements hook_entity_presave().
 */
function classrooms_core_entity_presave(EntityInterface $entity) {
  if (!$entity instanceof FieldableEntityInterface) {
    return;
  }

  if ($entity->bundle() === 'room') {
    if ($entity->hasField('field_room_building_id') && $entity->hasField('field_room_room_id')) {
      if (!empty($entity->get('field_room_building_id')->target_id && !empty($entity->get('field_room_room_id')->value))) {

        $building_id = $entity->get('field_room_building_id')->target_id;
        $room_id = $entity->get('field_room_room_id')->value;
        $building = Drupal::entityTypeManager()->getStorage('building')->load($building_id);

        // Set title programmatically based on building and room id.
        $title = $building->label() . " " . $room_id;
        $entity->setTitle($title);
      }
    }
  }
}
