<?php

/**
 * @file
 * Primary module hooks for Housing Core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function housing_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_residence_hall_edit_form':
    case 'node_residence_hall_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}
