<?php

/**
 * @file
 * Primary module hooks for Housing Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_form_alter().
 */
function housing_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_residence_hall_edit_form':
    case 'node_residence_hall_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}

/**
 * Implements hook_preprocess_field().
 */
function housing_core_preprocess_field(&$variables, $hook) {
  switch ($variables['element']['#field_name']) {
    case 'field_residence_hall_who_lives':
      if (!isset($variables['title_attributes']['class'])) {
        $variables['title_attributes']['class'] = '';
      }
      $variables['title_attributes']['class'] .= 'h4 headline headline--serif headline--underline';

      break;

    case 'field_residence_hall_neighborhd':
    case 'field_residence_hall_population':
    case 'field_residence_hall_year_built':
    case 'field_residence_hall_building':
      if (!isset($variables['attributes']['class'])) {
        $variables['attributes']['class'] = '';
      }
      $variables['attributes']['class'] .= 'badge badge--secondary';

      break;

    case 'field_residence_hall_getting':
    case 'field_residence_hall_meet_us':
      if (!isset($variables['title_attributes']['class'])) {
        $variables['title_attributes']['class'] = '';
      }
      $variables['title_attributes']['class'] .= 'h2 headline headline--serif headline--underline';

      break;

    case 'field_residence_hall_floor_plans':

      foreach ($variables['items'] as $delta => $item) {
        /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
        $paragraph = $item['content']['#paragraph'];
        // @todo Refactor to use nullsafe operator when we switch to Php 8+.
        $floorplan_field = $paragraph->get('field_housing_floor_plan_type')->first();
        if (!isset($floorplan_field)) {
          continue;
        }
        $floorplan_reference = $floorplan_field->get('entity');
        if (!isset($floorplan_reference)) {
          continue;
        }
        $floorplan_entity_adapter = $floorplan_reference->getTarget();
        if (!isset($floorplan_entity_adapter)) {
          continue;
        }
        /** @var \Drupal\taxonomy\TermInterface $floorplan_term */
        $floorplan_term = $floorplan_entity_adapter->getValue();
        if (!isset($floorplan_term)) {
          continue;
        }
        $variables['items'][$delta]['tab_label'] = $floorplan_term->getName();

      }

      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function housing_core_preprocess_layout(&$variables) {
  /** @var \Drupal\Core\Layout\LayoutDefinition $layout */
  $layout = $variables['layout'];

  // Process the header layout.
  if ($layout->id() === 'layout_header') {
    $node = \Drupal::routeMatch()->getParameter('node');
    $node = ($node ?? \Drupal::routeMatch()->getParameter('node_preview'));
    if ($node instanceof NodeInterface) {
      if (in_array($node->getType(), [
        'residence_hall',
      ])) {
        if (!isset($variables['banner_attributes'])) {
          $variables['banner_settings'] = [];
        }
      }
      switch ($node->getType()) {

        case 'residence_hall':
          $variables['#attached']['library'][] = 'housing_core/pannellum';
          if ($node->hasField('field_image') && !$node->get('field_image')->isEmpty()) {

            // Set the featured image display.
            $variables['featured_image_display'] = 'medium';

            // Set banner defaults.
            $variables['banner_settings']['transparent'] = TRUE;
            $variables['banner_settings']['horizontal_align'] = 'center';
            $variables['banner_settings']['vertical_align'] = 'center';
          }
          break;

      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function housing_core_preprocess_paragraph(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $paragraph = $variables['paragraph'];
    $parent = $paragraph->getParentEntity();
    if ($parent instanceof ContentEntityInterface) {
      $housing_cta = [
        'field_residence_hall_cta' => 'bg--white card--centered card--alignment-center media--border card--stacked',
        'field_residence_hall_contact' => 'card--centered-left card--alignment-left media--border card--media-left',
        'field_residence_hall_bldg_links' => 'card--centered-left card--alignment-left media--border card--media-left',
      ];
      $id = $paragraph->id();
      foreach ($housing_cta as $field => $label) {
        if ($parent->hasField($field)) {
          foreach ($parent->get($field)->getValue() as $item) {
            if ($item['target_id'] === $id) {
              $variables['cta_card_classes'] = $label;
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function housing_core_theme($existing, $type, $theme, $path) {
  return [
    'field__node__field_residence_hall_floor_plans__residence_hall' => [
      'template' => 'field--node--field-residence-hall-floor-plans--residence-hall',
      'base hook' => 'field',
    ],
    'paragraph__housing_cta__default' => [
      'template' => 'paragraph--housing-cta--default',
      'base hook' => 'paragraph',
    ],
    'field__node__field_residence_hall_furnishings__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-furnishings--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_neighborhd__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-neighborhd--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_room_type__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-room-type--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_amenities__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-amenities--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_bath_images__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-bath-images--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_rates__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-rates--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_cta__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-cta--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_emerg_title__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-emerg-title--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_emerg_text__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-emerg-text--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_emerg_link__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-emerg-link--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_population__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-population--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_year_built__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-year-built--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__field_residence_hall_building__residence_hall__default' => [
      'template' => 'field--node--field-residence-hall-building--residence-hall--default',
      'base hook' => 'field',
    ],
    'field__node__title__residence_hall__default' => [
      'template' => 'field--node--title--residence-hall--default',
      'base hook' => 'field',
    ],
  ];
}
