<?php

/**
 * @file
 * Primary module hooks for Uiowa Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\google_tag\Entity\Container;

/**
 * Implements hook_page_attachments().
 */
function uiowa_core_page_attachments(&$page) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    // Load campus-wide Google Tag in PROD.
    $env = getenv('AH_PRODUCTION');
    if ($env == 1) {
      $page['#attached']['library'][] = 'uiowa_core/gtag';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function uiowa_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'google_tag_container':
      $uiowa_core_gtag = \Drupal::config('uiowa_core.settings')->get('uiowa_core.gtag');
      // Inform on configuration form that the functionality is
      // currently being blocked from being inserted.
      if ($uiowa_core_gtag == '0') {
        \Drupal::messenger()
          ->addWarning(t('Local Google Tag Manager container snippets are currently blocked from being inserted on this website. Please contact the ITS Help Desk about enabling this functionality.'));
      }
      break;

    // Add delete forms as the types of protected blocks changes.
    case 'block_content_uiowa_text_area_delete_form':
      // Get current block uuid.
      $block = $form_state
        ->getFormObject()
        ->getEntity();
      $uuid = $block->uuid();

      // Get protected settings from uiowa_core.
      $protected = \Drupal::config('uiowa_core.protected');
      // If protected...
      if ($protected->get('protect')) {
        // Get uuids of protected blocks.
        $protected_blocks = $protected->get('protected_blocks');
        $uuids = array_keys($protected_blocks);

        // See if current block matches any protected and prevent deletion.
        if (in_array($uuid, $uuids)) {
          \Drupal::messenger()->addWarning(t('This block is protected from deletion. Remove content from the block instead.'));
          $form['actions']['submit']['#disabled'] = TRUE;
        }
      }
      break;

    // @todo Move this to a more appropriate location.
    case 'node_area_of_study_form':
      foreach ([
        'field_area_of_study_majors',
        'field_area_of_study_minors',
        'field_area_of_study_certificates',
        'field_area_of_study_preprof',
        'field_area_of_study_online',
      ] as $program_type) {

        if (isset($form[$program_type])) {
          $program_toggle = $program_type . '_toggle';
          $form[$program_toggle] = [
            '#type' => 'checkbox',
            '#title' => $form[$program_type]['widget']['#title'],
            '#weight' => $form[$program_type]['#weight'] - 1,
            '#name' => $program_toggle,
          ];

          $form['#group_children'][$program_toggle] = 'group_area_of_study_program_type';
          $form['#fieldgroups']['group_area_of_study_program_type']->children[] = $program_toggle;

          $form[$program_type] += [
            '#states' => [
              'visible' => [
                ':input[name="' . $program_toggle . '"]' => [
                  'checked' => TRUE,
                ],
              ],
            ],
          ];
        }
      }
      break;
  }
}

/**
 * {@inheritdoc}
 */
function uiowa_core_google_tag_insert_alter(&$satisfied, Container $container) {
  $uiowa_core_gtag = \Drupal::config('uiowa_core.settings')->get('uiowa_core.gtag');
  $env = getenv('AH_PRODUCTION');
  // Determine if site specific Google Tag should be inserted.
  if ($uiowa_core_gtag == '0' || $env == 0) {
    $satisfied = FALSE;
  }
}
