<?php

/**
 * @file
 * Contains hr_core.module.
 */

/**
 * Implements hook_uip_classes_alter().
 */
function hr_core_uip_classes_alter(&$options, $entity, $bundle) {
  switch ($bundle) {
    case 'card':
      $options['card--img-icon'] = 'Card Image Icon';
      $options['card--title-overlay-bottom-left'] = 'Title Overlay Bottom Left';
      $options['card--title-overlay-top-right'] = 'Title Overlay Top right';
      break;

  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function hr_core_theme_suggestions_paragraph_alter(&$suggestions, $variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $paragraph = $variables["elements"]["#paragraph"];
    $bundle = $paragraph->bundle();
    switch ($bundle) {
      case 'card':
        if ($paragraph->hasField('field_uip_classes') && !$paragraph->get('field_uip_classes')->isEmpty()) {
          $classes = $paragraph->get('field_uip_classes')->getValue();
          // Clean array of classes selected.
          $classes = array_column($classes, 'value');
          // Check for title-overlay classes and provide template.
          $title_overlay_options = [
            'card--title-overlay-top-right',
            'card--title-overlay-bottom-left',
          ];
          $result = array_intersect($title_overlay_options, $classes);
          if ($result) {
            $suggestions[] = 'paragraph__card__title_overlay';
          }
        }
        break;

    }
  }
}
