<?php

/**
 * @file
 * Custom functionality for the Commencement website.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\commencement_core\EventsProcessor;

/**
 * Import events.
 */
function commencement_core_import_events() {
  // Check that this process is being called with
  // admin permissions.
  /** @var Drupal\uiowa_core\Access\UiowaCoreAccess $check */
  $check = \Drupal::service('uiowa_core.access_checker');
  /** @var Drupal\Core\Access\AccessResultInterface $access */
  $access = $check->access(\Drupal::currentUser()->getAccount());
  if (!$access) {
    return 'This is a restricted process.';
  }

  $logger = \Drupal::logger('commencement_core');
  $logger->notice('Checking for events.');

  $sync_service = new EventsProcessor();
  $sync_service->init();
  $sync_service->process();

  $arguments = [
    '@created' => $sync_service->getCreated(),
    '@updated' => $sync_service->getUpdated(),
    '@deleted' => $sync_service->getDeleted(),
    '@skipped' => $sync_service->getSkipped(),
  ];
  $message = t('Commencement event content sync completed. @created events were created, @updated updated, @deleted deleted, @skipped skipped. That is neat.', $arguments);
  return $message;
}
