<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function commencement_core_preprocess_field__field_media_file(&$variables) {
  if (isset($variables['element']['#object']) && $variables['element']['#object'] instanceof \Drupal\media\Entity\Media) {
    $media = $variables['element']['#object'];
    /** @var \Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem $referring_item */
    $referring_item = $media->_referringItem;
    if (!is_null($referring_item)) {
      $parent = $referring_item->getParent();
      if ($parent->getName() === 'field_session_program' && isset($variables['element'][0]['#description'])) {
        $variables['items'][0]['content']['#description'] = t('View program');
      }
    }
  }
}
