<?php

/**
 * @file
 * Custom functionality the Emergency website.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\emergency_core\AlertsProcessor;

/**
 * Implements hook_form_alter().
 */
function emergency_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_hawk_alert_form':
    case 'node_hawk_alert_edit_form':
      // To prevent duplicate alerts, identifier field is not editable.
      $form['field_hawk_alert_identifier']['#disabled'] = TRUE;
      break;
  }
}

/**
 * Import alerts.
 */
function emergency_core_import_alerts() {
  // Check that this process is being called with
  // admin permissions.
  /** @var Drupal\uiowa_core\Access\UiowaCoreAccess $check */
  $check = \Drupal::service('uiowa_core.access_checker');
  /** @var Drupal\Core\Access\AccessResultInterface $access */
  $access = $check->access(\Drupal::currentUser()->getAccount());
  if (!$access) {
    return 'This is a restricted process.';
  }

  $logger = \Drupal::logger('emergency_core');
  $logger->notice('Starting the hawk alert content sync.');

  $sync_service = new AlertsProcessor();
  $sync_service->init();
  $sync_service->process();

  $arguments = [
    '@created' => $sync_service->getCreated(),
    '@skipped' => $sync_service->getSkipped(),
  ];
  $message = t('Hawk alerts content sync completed. @created alerts were created and @skipped skipped. That is neat.', $arguments);
  $logger->notice($message);
  return $message;
}
