<?php

/**
 * @file
 * Contains sitenow_accordion.module.
 */

/**
 * Implements hook_preprocess_field().
 */
function sitenow_accordion_preprocess_field(&$variables) {

  switch ($variables["element"]["#field_name"]) {
    case 'field_accordion_item':
      // Add parent_id.
      $variables['parent_id'] = $variables["element"]["#object"]->id();
      // Prepare items array.
      $items = [];
      foreach ($variables['items'] as $item) {
        $items[] = $item['content'];
      }
      $variables['items'] = $items;
      break;
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function sitenow_accordion_preprocess_paragraph__accordion_item(&$variables) {
  /** @var Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  /** @var Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');

  if (!$admin_context->isAdminRoute()) {
    $variables['accordion_parent'] = 'accordion-' . $paragraph->getParentEntity()->id();
    $variables['id'] = $paragraph->id();
  }
}
