project:
  machine_name: sitesalvee
  human_name: alvee.sites.uiowa.edu
  local:
    hostname: sitesalvee.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: sitesalvee.prod
drupal:
  db:
    database: alvee_sites_uiowa_edu
uiowa:
  requester: mehsan
  site-name: 'Alvee Ehsan'
