#!/usr/bin/env bash

# Override BLTs default TravisCI run_tests script since it was not invoking
# drupal:install for some reason. Possibly related to travis_wait.

set -ev

blt blt:telemetry:disable --no-interaction
blt validate --no-interaction
blt setup -D drush.alias='${drush.aliases.ci}' --no-interaction --verbose
blt tests --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose

set +ev
