#!/usr/bin/env bash

# Override BLTs default TravisCI run_tests script since it was not invoking
# drupal:install for some reason. Possibly related to travis_wait.

set -ev

blt validate:all --no-interaction
blt setup --define drush.alias='${drush.aliases.ci}' --define travis.profile=$TRAVIS_PROFILE --no-interaction --verbose
blt tests:all --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose

set +ev
