<?php

/**
 * @file
 * Primary module hooks for SPPA Core module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_state_options_alter().
 */
function sppa_core_state_options_alter(&$options, $entity, $bundle) {
  // Add additional options to states list for SPPA.
  $options['US'] = 'United States';
  $options['INTL'] = 'International';
}

/**
 * Implements hook_allowed_values_function().
 */
function sppa_core_opportunity_types_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [
    'jobs' => 'Jobs',
    'internships' => 'Internships',
    'fellowships' => 'Fellowships',
  ];
  return $options;
}

/**
 * Implements hook_allowed_values_function().
 */
function sppa_core_degrees_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  $options = [
    'URP' => 'URP',
    'MPA' => 'MPA',
  ];
  return $options;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sppa_core_preprocess_page(&$variables) {
  $c3d_api = \Drupal::service('uiowa_concept3d.api');
  $data = $c3d_api->getLocations();
  $marker_mapping = [];
  if ($data) {

    foreach($data as $key => $item) {
      if (isset($item->reference[0])) {
        $marker_mapping[$item->reference[0]] = $item->id;
      }
    }
  }
  $foo = $marker_mapping;
}
