<?php

/**
 * @file
 * Contains sitenow_card.module.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function sitenow_blockquote_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__blockquote__default' => [
      'template' => 'paragraph--blockquote--default',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_uip_classes_alter().
 */
function sitenow_blockquote_uip_classes_alter(&$options, $entity, $bundle) {
  switch ($bundle) {
    case 'blockquote':
      $options['blockquote-center'] = 'Align Center';
      $options['blockquote-right'] = 'Align Right';
      break;

  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function sitenow_blockquote_theme_suggestions_field_alter(&$suggestions, $variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    switch ($variables['element']['#field_name']) {
      case 'field_blockquote_cite':
      case 'field_blockquote_footer':
        $suggestions[] = 'field__no_markup';
        break;

    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_blockquote_preprocess_paragraph__blockquote(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    // Create new blockquote attributes.
    $variables['blockquote_attributes'] = new Attribute();
    $variables['blockquote_attributes']->addClass('blockquote');
  }
}
