<?php

/**
 * @file
 * Primary module hooks for Iowa Summer Writing Festival Core module.
 */

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function iowasummerwritingfestival_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_event_form':
    case 'node_event_edit_form':
      $form['field_event_genre']['#attributes']['class'][] = 'multi--column';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function iowasummerwritingfestival_core_theme($existing, $type, $theme, $path) {
  return [
    'field__node__field_event_registration_link__event__default' => [
      'template' => 'field--node--field-event-registration-link--event--default',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Set dynamic allowed values for the field_event_genre field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function iowasummerwritingfestival_core_field_event_genre_options_allowed_values(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, bool &$cacheable) : array {
  $options = [];

  // Set the allowed values for the field_event_genre field to the following.
  $options = [
    'Childrens' => 'Children\'s',
    'Essay' => 'Essay',
    'Fantasy' => 'Fantasy',
    'Fiction' => 'Fiction',
    'HybridForms' => 'Hybrid Forms',
    'Memoir' => 'Memoir',
    'MiddleGrade' => 'Middle Grade',
    'Nonfiction' => 'Nonfiction',
    'Novel' => 'Novel',
    'Playwriting' => 'Playwriting',
    'Poetry' => 'Poetry',
    'ScienceFiction' => 'Science Fiction',
    'Screenwriting' => 'Screenwriting',
    'ShortStory' => 'Short Story',
    'SpeculativeFiction' => 'Speculative Fiction',
    'YoungAdult' => 'Young Adult',
  ];
  return $options;
}
