<?php

/**
 * @file
 * Primary module hooks for Iowa Summer Writing Festival Core module.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function iowasummerwritingfestival_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_event_form':
    case 'node_event_edit_form':
      $form['field_event_genre']['#attributes']['class'][] = 'multi--column';
      break;
  }
}

/**
 * Implements hook_theme().
 */
function iowasummerwritingfestival_core_theme($existing, $type, $theme, $path) {
  return [
    'field__node__field_event_registration_link__event__default' => [
      'template' => 'field--node--field-event-registration-link--event--default',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function iowasummerwritingfestival_core_theme_suggestions_field_alter(array &$suggestions, array &$variables) {
  switch ($variables['element']['#field_name']) {
    case 'field_event_genre':
      $suggestions[] = 'field__comma_separated';
      break;
  }
}

/**
 * Set dynamic allowed values for the field_event_type field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function iowasummerwritingfestival_core_field_event_type_options_allowed_values(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, bool &$cacheable) : array {
  $options = [];

  // Set the allowed values for the field_event_type field to the following.
  $options = [
    'Banquet' => 'Banquet',
    'BoardMeeting' => 'Board Meeting',
    'Colloquium' => 'Colloquium',
    'Conference' => 'Conference',
    'Convention' => 'Convention',
    'Course' => 'Course',
    'Exhibition' => 'Exhibition',
    'Exposition' => 'Exposition',
    'Fair' => 'Fair',
    'Festival' => 'Festival',
    'Fundraiser' => 'Fundraiser',
    'Gala' => 'Gala',
    'GeneralSession' => 'General Session',
    'GreenMeeting' => 'Green Meeting',
    'Meetup' => 'Meetup',
    'NetworkingEvent' => 'Networking Event',
    'Party' => 'Party',
    'PressConference' => 'Press Conference',
    'ProductLaunch' => 'Product Launch',
    'Reception' => 'Reception',
    'Retreat' => 'Retreat',
    'Round-Table' => 'Round-Table',
    'Seminar' => 'Seminar',
    'Session' => 'Session',
    'SocialEvent' => 'Social Event',
    'Symposium' => 'Symposium',
    'TradeShow' => 'Trade Show',
    'Workshop' => 'Workshop',
  ];
  return $options;
}

/**
 * Set dynamic allowed values for the field_event_genre field.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   The entity being created if applicable.
 * @param bool $cacheable
 *   Boolean indicating if the results are cacheable.
 *
 * @return array
 *   An array of possible key and value options.
 *
 * @see options_allowed_values()
 */
function iowasummerwritingfestival_core_field_event_genre_options_allowed_values(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, bool &$cacheable) : array {
  $options = [];

  // Set the allowed values for the field_event_genre field to the following.
  $options = [
    'AllGenres' => 'All Genres',
    'Childrens' => 'Children\'s',
    'Essay' => 'Essay',
    'Fiction' => 'Fiction',
    'HybridForms' => 'Hybrid Forms',
    'Memoir' => 'Memoir',
    'Nonfiction' => 'Nonfiction',
    'Novel' => 'Novel',
    'Playwriting' => 'Playwriting',
    'Poetry' => 'Poetry',
    'Sci-Fi/Fantasy' => 'Sci-Fi/Fantasy',
    'Screenwriting' => 'Screenwriting',
    'ShortStory' => 'Short Story',
    'YoungAdult' => 'Young Adult',
  ];
  return $options;
}
