<?php

/**
 * @file
 * Primary module hooks for Uiowa Search module.
 */

/**
 * Implements hook_theme().
 */
function uiowa_search_theme($existing, $type, $theme, $path) {
  $uiowa_search_config = \Drupal::config('uiowa_search.settings');
  return [
    'uiowa_search' => [
      'variables' => [
        'config' => $uiowa_search_config->get('uiowa_search'),
        'search_form' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function uiowa_search_page_attachments(&$page) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $page['#attached']['library'][] = 'uiowa_search/search-form';
  }
}
