<?php

/**
 * @file
 * Custom functionality the Facilities website.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function facilities_core_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] === 'field_building_honoree_name') {
    // Change label for output.
    $variables['element']['#title'] = 'Honoree';
    $variables['label'] = 'Honoree';
    $node = $variables['element']['#object'];
    // Append the last name if it exists.
    if (!$node->get('field_building_honoree_last_name')->isEmpty()) {
      $last = $node->get('field_building_honoree_last_name')->value;
      // Loop through and overwrite the value.
      foreach ($variables['items'] as $key => $item) {
        $variables['items'][$key]['content']['#context']['value'] .= ' ' . $last;
      }
    }
  }
}
