<?php

/**
 * @file
 * Install tasks.
 */

/**
 * Implements hook_install().
 */
function studentlife_migrate_install() {
  module_load_install('sitenow_migrate');
  sitenow_migrate_migration_install('studentlife');
}

/**
 * Implements hook_uninstall().
 */
function studentlife_migrate_uninstall() {
  module_load_install('sitenow_migrate');
  sitenow_migrate_migration_uninstall('studentlife');
}
