<?php

/**
 * @file
 * Primary module hooks for Tippie Core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 */
function tippie_core_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (isset($element['#webform_key'])) {
    if ($element['#webform_key'] === 'visitorid') {
      $element['#element_validate'][] = [
        'Drupal\tippie_core\Validate\PardotVisitorIdConstraint',
        'validate',
      ];
    }
    // With Acquia varnish, Webform can't pre-populate Google Click ID (gclid).
    if ($element['#webform_key'] === 'gclid') {
      $element['#attached']['library'][] = 'tippie_core/get_gclid';
    }
  }
}
