<?php

/**
 * @file
 * Primary module hooks for Uiowa Intranet module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Url;

/**
 * Implements hook_restrict_ip_access_denied_page_alter().
 */
function uiowa_intranet_restrict_ip_access_denied_page_alter(&$page) {
  if (isset($page['access_denied'])) {
    unset($page['access_denied']);
  }
  // Create our own access denied page and login.
  $page['main'] = [
    '#type' => 'html_tag',
    '#tag' => 'main',
    '#attributes' => [
      'role' => 'main',
      'class' => 'page__container',
    ],
  ];
  $page['main']['access_denied_title_container'] = [
    '#type' => 'html_tag',
    '#tag' => 'div',
    '#attributes' => [
      'class' => [
        'section-padding__top-extra',
        'layout--title',
        'layout__container',
        'layout',
      ],
    ],
  ];
  $page['main']['access_denied_title_container']['access_denied_title'] = [
    '#markup' => t('Access denied'),
    '#prefix' => '<h1 class="page-title bold-headline--serif bold-headline text-align-center">',
    '#suffix' => '</h1>',
  ];
  $page['main']['access_denied_message'] = [
    '#markup' => t('You are not authorized to access this page.'),
    '#prefix' => '<p class="text-align-center">',
    '#suffix' => '</p>',
  ];
  $page['main']['continuation_message'] = [
    '#markup' => t('Continue by logging in with your HawkID.'),
    '#prefix' => '<p class="text-align-center">',
    '#suffix' => '</p>',
  ];
  if (isset($page['logout_link'])) {
    $page['main']['logout_link'] = $page['logout_link'];
    unset($page['logout_link']);
  }
  if (isset($page['login_link'])) {
    $page['main']['login_link'] = [
      '#type' => 'link',
      '#title' => t('HawkID Login'),
      '#url' => Url::fromRoute('samlauth.saml_controller_login'),
      '#prefix' => '<p class="text-align-center">',
      '#suffix' => '</p>',
      '#attributes' => [
        'class' => [
          'bttn',
          'bttn--primary',
          'bttn--caps',
        ],
      ],
    ];
    unset($page['login_link']);
  }
}
