<?php

/**
 * @file
 * Dynamically display Hawk Alerts from the UI emergency alert system.
 */

/**
 * Implements hook_block_info().
 */
function uiowa_alerts_block_info() {
  $blocks['alerts'] = [
    'info' => t('UIowa Alerts'),
    'cache' => DRUPAL_NO_CACHE,
  ];
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function uiowa_alerts_block_view($delta) {
  $block = [];

  if ($delta == 'alerts') {
    $module_path = drupal_get_path('module', 'uiowa_alerts');
    $no_alerts_message = trim(variable_get('uiowa_alerts_no_alerts_message', ''));
    $filtered_message = filter_xss($no_alerts_message, $allowed_tags = array('a', 'p', 'div', 'em', 'strong'));
    $source = variable_get('uiowa_alerts_source', 'json_production');
    switch ($source) {
      case 'json_production':
        $source_url = 'https://emergency.uiowa.edu/api/active.json';
        break;

      case 'json_test':
        $source_url = 'https://emergency.stage.drupal.uiowa.edu/api/active.json';
        break;
    }

    $block['content'] = array(
      '#markup' => '<div class="uiowa-alerts-wrapper"></div>',
      '#attached' => array(
        'js' => array(
          $module_path . '/js/moment.min.js',
          $module_path . '/js/uiowa_alerts.js',
          array(
            'data' => array(
              'uiowaAlerts' => array(
                'alertSource' => $source_url,
                'noAlertsMessage' => $filtered_message,
              ),
            ),
            'type' => 'setting',
          ),
        ),
      ),
    );
  }

  return $block;
}
