<?php

/**
 * @file
 * Contains sitenow_periodical.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\pathauto\Entity\PathautoPattern;

/**
 * Implements hook_entity_presave().
 */
function sitenow_periodical_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'publication_issue':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_issue_season_year')->value . " Volume " . $entity->get('field_issue_volume')->value . " Issue " . $entity->get('field_issue_number')->value;
      $entity->setTitle($output);
      break;

  }
}

/**
 * Implements hook_pathauto_pattern_alter().
 */
function sitenow_periodical_pathauto_pattern_alter(&$pattern, array $context) {
  if ($context['module'] === 'node' && $context['bundle'] === 'article') {
    $node = $context['data']['node'];
    $issue = $node->get('field_article_issue');

    // Change URL alias pattern if article is part of an issue.
    if (!$issue->isEmpty()) {
      $new_pattern = PathautoPattern::load('article_publication')->getPattern();
    }
    else {
      $new_pattern = PathautoPattern::load('article')->getPattern();
    }
    $pattern->setPattern($new_pattern);
  }
}
