<?php

/**
 * @file
 * Contains sitenow_periodical.module.
 */

/**
 * Implements hook_pathauto_pattern_alter().
 */
function sitenow_periodical_pathauto_pattern_alter(&$pattern, array $context) {
  if ($context['module'] === 'node' && $context['bundle'] === 'article') {
    $node = $context['data']['node'];
    $issue = $node->get('field_article_issue');

    // Change URL alias pattern if article is part of an issue.
    if (!$issue->isEmpty()) {
      $new_pattern = Drupal\pathauto\Entity\PathautoPattern::load('article_publication')->getPattern();
    }
    else {
      $new_pattern = Drupal\pathauto\Entity\PathautoPattern::load('article')->getPattern();
    }
    $pattern->setPattern($new_pattern);
  }
}
