<?php

/**
 * @file
 * Contains grad_thesis_defense.module.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\grad_thesis_defense\Entity\ThesisDefense;
use Drupal\layout_builder\Form\ConfigureBlockFormBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function grad_thesis_defense_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['thesis_defense'])) {
    $bundles['node']['thesis_defense']['class'] = ThesisDefense::class;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function grad_thesis_defense_entity_extra_field_info(): array {
  $extra = [];
  // Disclaimer text.
  $extra['node']['thesis_defense']['display']['field_thesis_defense_disclaimer'] = [
    'label' => t('Disclaimer'),
    'description' => t('Disclaimer text to be printed with each node.'),
    'weight' => 1,
    'visible' => TRUE,
  ];

  return $extra;
}

/**
 * Implements hook_form_alter().
 */
function grad_thesis_defense_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_thesis_defense_form':
    case 'node_thesis_defense_edit_form':
      // These are imported fields that editors should not interact with.
      $form['title']['#disabled'] = TRUE;
      $form['field_thesis_defense_title']['#disabled'] = TRUE;
      $form['field_thesis_defense_sync_id']['#disabled'] = TRUE;
      $form['field_thesis_defense_location']['#disabled'] = TRUE;
      $form['field_thesis_defense_program']['#disabled'] = TRUE;
      $form['field_thesis_defense_date']['#disabled'] = TRUE;
      $form['field_thesis_defense_chairs']['#disabled'] = TRUE;
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function grad_thesis_defense_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof ConfigureBlockFormBase) {
    /** @var \Drupal\layout_builder\SectionComponent $component */
    $component = $form_object->getCurrentComponent();
    $block = $component->getPlugin();
    switch ($block->getPluginId()) {
      case 'views_block:thesis_defenses-block_thesis_defenses':
        if ($form['settings']['override']['items_per_page']) {
          $form['settings']['override']['items_per_page']['#default_value'] = 50;
        }
        break;
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function grad_thesis_defense_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode): void {
  if ($node->bundle() === 'thesis_defense') {
    if ($display->getComponent('field_thesis_defense_disclaimer')) {
      $build['field_thesis_defense_disclaimer'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => [
            'field',
            'field--name-field-thesis-defense-disclaimer',
            'field--type-list-string',
            'field--label-inline',
          ],
        ],
      ];
      $build['field_thesis_defense_disclaimer']['label'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#value' => t('Disclaimer'),
        '#attributes' => [
          'class' => ['field__label visually-hidden'],
        ],
      ];
      $build['field_thesis_defense_disclaimer']['value'] = [
        '#type' => 'html_tag',
        '#tag' => 'div',
        '#value' => '<em>' . t('Thesis title listed for defense is subject to change.') . '</em>',
        '#attributes' => [
          'class' => ['field__item'],
        ],
      ];
    }
  }
}

/**
 * Implements hook_preprocess_field().
 */
function grad_thesis_defense_preprocess_field(&$variables, $hook) {
  switch ($variables['element']['#field_name']) {
    case 'field_thesis_defense_date':
      uiowa_core_set_field_icon($variables, 'fas fa-clock');

      break;

    case 'field_thesis_defense_location':
      uiowa_core_set_field_icon($variables, 'fas fa-map-marker-alt');

      break;

    case 'field_thesis_defense_title':
      if ($variables['element']['#view_mode'] == 'full') {
        $variables['item_tag'] = 'h2';
        uiowa_core_set_attributes($variables, 'element--light-intro');
      }

      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function grad_thesis_defense_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if ($form['#id'] === 'views-exposed-form-thesis-defenses-block-thesis-defenses') {
    $form['#attached']['library'][] = 'uids_base/view-bef';
  }
}

/**
 * Implements hook_preprocess_views_view_unformatted().
 */
function grad_thesis_defense_preprocess_views_view_unformatted(array &$variables): void {
  $view = $variables['view'];

  if ($view->id() === 'thesis_defenses' && $view->current_display === 'block_thesis_defenses' && !empty($variables['title'])) {
    $variables['views_heading_classes'] = array_merge(
      $variables['views_heading_classes'] ?? [],
      [
        'headline',
        'headline--serif',
        'headline--underline',
      ],
    );
  }
}

/**
 * Implements hook_views_pre_view().
 */
function grad_thesis_defense_views_pre_render(ViewExecutable $view): void {
  if ($view->id() === 'thesis_defenses' && $view->current_display === 'block_thesis_defenses') {
    $view->element['#cache']['tags'][] = 'time:daily';
  }
}

/**
 * Implements hook_views_pre_view().
 */
function grad_thesis_defense_views_pre_view(ViewExecutable $view, $display_id, array &$args): void {
  // Default the filter to today if exposed.
  if ($view->id() === 'thesis_defenses' && $display_id === 'block_thesis_defenses') {
    $exposed_input = $view->getExposedInput();
    // If the date filter is not set and exposed, default it to today.
    $exposed = $view->display_handler->getOption('block_config')['exposed']['filter-field_thesis_defense_date_value']['exposed'];
    if (empty($exposed_input['combine'])) {
      if (empty($exposed_input['field_thesis_defense_date_value']) && $exposed) {
        $today = (new DrupalDateTime())->format('Y-m-d');
        $exposed_input['field_thesis_defense_date_value'] = $today;
        $view->setExposedInput($exposed_input);
      }
    }
  }
}
