<?php

/**
 * @file
 * Contains grad_thesis_defense.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 */
function grad_thesis_defense_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'thesis_defense':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . ' ' . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}

/**
 * Implements hook_preprocess_field().
 */
function grad_thesis_defense_preprocess_field(&$variables, $hook) {
  switch ($variables['element']['#field_name']) {
    case 'field_thesis_defense_date':
      uiowa_core_set_field_icon($variables, 'fas fa-calendar-alt');

      break;

    case 'field_thesis_defense_location':
      uiowa_core_set_field_icon($variables, 'fas fa-map-marker-alt');

      break;
  }
}

/**
 * Implements hook_theme().
 */
function grad_thesis_defense_theme($existing, $type, $theme, $path) {
  return [
    'node__thesis_defense__teaser' => [
      'template' => 'node--thesis-defense--teaser',
      'base hook' => 'node',
    ],
  ];
}
