<?php

/**
 * @file
 * Primary module hooks for SiteNow Alerts module.
 */

use Drupal\sitenow_alerts\Entity\Alert;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function sitenow_alerts_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['alert'])) {
    $bundles['node']['alert']['class'] = Alert::class;
  }
}

/**
 * Implements hook_preprocess_field().
 */
function sitenow_alerts_preprocess_field(&$variables, $hook) {
  switch ($variables['element']['#field_name']) {

    case 'field_alert_category':
      if ($variables['element']['#view_mode'] === 'teaser') {
        // Set the categories inline and make them badges.
        uiowa_core_set_attributes($variables, 'element--inline');
        foreach ($variables['items'] as &$item) {
          $field_label = $item['content']['#plain_text'];
          unset($item['content']['#plain_text']);
          $item['content']['#markup'] = '<span class="badge badge--primary">' . $field_label . '</span>';
        }
      }
      break;

  }
}
