<?php

/**
 * @file
 * Installation functions for sppa_migrate module.
 */

/**
 * Implements hook_install().
 */
function slis_migrate_install() {
  \Drupal::moduleHandler()->loadInclude('sitenow_migrate', 'install');
  sitenow_migrate_migration_install('slis');
}

/**
 * Implements hook_uninstall().
 */
function slis_migrate_uninstall() {
  \Drupal::moduleHandler()->loadInclude('sitenow_migrate', 'install');
  sitenow_migrate_migration_uninstall('slis');
}
