adding:
  dependencies:
    config:
      - field.field.node.person.field_person_ighn_college
      - field.field.node.person.field_person_ighn_department
      - field.field.node.person.field_person_ighn_global_regions
      - field.field.node.person.field_person_ighn_languages
  hidden:
    field_person_ighn_college: true
    field_person_ighn_department: true
    field_person_ighn_global_regions: true
    field_person_ighn_languages: true
removing: {  }
