adding:
  dependencies:
    config:
      - field.field.node.person.field_person_ighn_college
      - field.field.node.person.field_person_ighn_department
      - field.field.node.person.field_person_ighn_global_regions
      - field.field.node.person.field_person_ighn_languages
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: 3
            config_split_sequence_8a8h4ptgg2f74i4f:
              weight: 6
            config_split_sequence_mh2jcunktnqjnmaf:
              weight: 2
            config_split_sequence_4eq0pov6hr1goq0g:
              uuid: a3d92f9a-226d-49d1-8ab0-bac6a4000f74
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_global_regions'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: 5
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_41jv7f1jhl694dgl:
              uuid: 1908918b-2678-41a8-bf0f-991c9a3e1ef7
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_languages'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: 4
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_7l0n7a67s1eroubn:
              uuid: 4f0aaeea-47fb-4020-9b57-c75486e49913
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_department'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: hidden
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ', '
              weight: 0
              additional:
                layout_builder_styles_style:
                  block_margin_default_removed: block_margin_default_removed
              third_party_settings: {  }
            config_split_sequence_vdbgeaod1v3rnuv5:
              uuid: 7de465ca-f2ed-408b-a124-ba1cd03a66af
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_college'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: hidden
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ', '
              weight: 1
              additional:
                layout_builder_styles_style:
                  block_margin_default_removed: block_margin_default_removed
              third_party_settings: {  }
  hidden:
    field_person_ighn_college: true
    field_person_ighn_department: true
    field_person_ighn_global_regions: true
    field_person_ighn_languages: true
removing:
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: 1
            config_split_sequence_8a8h4ptgg2f74i4f:
              weight: 2
            config_split_sequence_mh2jcunktnqjnmaf:
              weight: 0
