adding:
  dependencies:
    config:
      - field.field.node.person.field_person_ighn_college
      - field.field.node.person.field_person_ighn_department
      - field.field.node.person.field_person_ighn_global_regions
      - field.field.node.person.field_person_ighn_languages
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: -1
            config_split_sequence_mh2jcunktnqjnmaf:
              weight: -2
            config_split_sequence_sdfdubcfp676eada:
              uuid: df7582fc-abd8-4a52-b677-6ee9ae28a294
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_languages'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: 1
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_r1qg4m5k7gee58f9:
              uuid: 78c349f0-6220-4654-8ece-a4fbabf84f1f
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_department'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: -4
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_ra6j3os4r4v69vv4:
              uuid: 9ceba469-b5c2-4cc5-ae0d-f3abeb605735
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_college'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: -3
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
            config_split_sequence_p83c5bnkp2iv4658:
              uuid: c6a6e3fd-87d7-41c4-a91a-f34af67640cb
              region: main
              configuration:
                id: 'field_block:node:person:field_person_ighn_global_regions'
                label: null
                label_display: null
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: above
                  settings:
                    link: false
                  third_party_settings:
                    field_delimiter:
                      delimiter: ''
              weight: 0
              additional:
                layout_builder_styles_style: {  }
              third_party_settings: {  }
  content:
    field_person_ighn_college:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 17
      region: content
    field_person_ighn_department:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 16
      region: content
    field_person_ighn_global_regions:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 18
      region: content
    field_person_ighn_languages:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 19
      region: content
removing:
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: 1
            config_split_sequence_mh2jcunktnqjnmaf:
              weight: 0
