adding:
  dependencies:
    config:
      - field.field.node.page.field_landing_page
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_7lcnfamb2lqejp09:
              uuid: 6542da94-df96-4cfd-a1f3-e0561b3be94d
              region: content
              configuration:
                id: 'field_block:node:page:field_landing_page'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: boolean
                  label: above
                  settings:
                    format: default
                    format_custom_false: ''
                    format_custom_true: ''
                  third_party_settings: {  }
              weight: 1
              additional: {  }
              third_party_settings: {  }
  content:
    field_landing_page:
      type: boolean
      label: above
      settings:
        format: default
        format_custom_false: ''
        format_custom_true: ''
      third_party_settings: {  }
      weight: 4
      region: content
removing: {  }
