<?php

/**
 * @file
 * SiteNow Dispatch module hooks.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_dispatch_preprocess_block(&$variables) {
  // Add block-webform class to dispatch forms which handles BG color combos.
  if (isset($variables['configuration'], $variables['configuration']['provider'])
    && $variables['configuration']['provider'] == 'sitenow_dispatch') {
    $variables['attributes']['class'][] = 'block-webform';
  }
}
