project:
  machine_name: siteskamelia-zaman-moon
  human_name: kamelia-zaman-moon.sites.uiowa.edu
  local:
    hostname: siteskamelia-zaman-moon.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: siteskamelia-zaman-moon.prod
drupal:
  db:
    database: kamelia_zaman_moon_sites_uiowa_edu
uiowa:
  requester: kammoon
  site-name: 'Kamelia Zaman Moon'
