<?php

/**
 * @file
 * Code for the uiowa Serv Hours module.
 */
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function uiowa_hours_theme($existing, $type, $theme, $path) {
  return [
    'block__inline_block__uiowa_hours' => [
      'render element' => 'content',
      'base hook' => 'block',
      'template' => 'block--inline-block--uiowa-hours',
      'path' => $path . '/templates',
    ],
    'field__field_uiowa_hours_status' => [
      'render element' => 'content',
      'base hook' => 'field',
      'template' => 'field--field-uiowa-hours-status',
      'path' => $path . '/templates',
    ],
    'field__field_uiowa_hours_fullcalendar.html.twig' => [
      'render element' => 'content',
      'base hook' => 'field',
      'template' => 'field--field-uiowa-hours-fullcalendar',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function uiowa_hours_preprocess_block(&$variables) {
  if ($variables['elements']['#plugin_id'] == 'inline_block:uiowa_hours') {
    $hours_status = 'hours-status-disabled';
    $calendar = 'fullcalendar-disabled';
    /** @var \Drupal\Block\Entity\Block $block */
    $block = $variables['elements']['content']['#block_content'];
    if ($block->get('field_uiowa_hours_status')->value == TRUE) {
      $hours_status = 'hours-status-enabled';
    }
    $variables["attributes"]['class'][] = $hours_status;

    $block = $variables['elements']['content']['#block_content'];
    if ($block->get('field_uiowa_hours_datepicker')->value == TRUE) {
      $calendar = 'fullcalendar-enabled';

    }
    $variables["attributes"]['class'][] = $calendar;
    }
  }
