<?php

/**
 * @file
 * Primary module hooks for Uiowa Core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function registrar_core_preprocess_block(&$variables) {
  switch ($variables['plugin_id']) {
    // Unset request info buttons.
    case 'academic_calendar_block':
      uiowa_core_set_attributes($variables, 'grid--twocol--25-75');
      break;

    // Add gpa calculator styles.
    case 'gpa_calculator':
      $variables['#attached']['library'][] = 'registrar_core/gpa-calculator';
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function registrar_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'gpa_calculator_form') {
    $form['gpa_row']['actions']['add_row']['#attributes']['class'][] = 'button--small';
    $form['gpa_row']['actions']['add_row']['#attributes']['class'][] = 'button--full-width';
    $form['#submit'][1] = '_second_submit';
  }
}

/**
 *
 */
function _second_submit(&$form, FormStateInterface $form_state) {
  $block_manager = \Drupal::service('plugin.manager.block');
  $skeletonLoader = $block_manager->createInstance('skeleton_load_block')->build();

  $calculatedGrades = $form['gpa_results_wrapper']['#markup']->getArguments();
  $current = $calculatedGrades['@current_gpa'];
  $cumulative = $calculatedGrades['@cumulative_gpa'];
  $form['#attached']['library'][] = 'uids_base/callout';
  $form['#attached']['library'][] = 'uids_base/callout';
  $form["gpa_results_wrapper"]['#prefix'] = '<blockquote class="callout bg--gray">';
  $form["gpa_results_wrapper"]['#suffix'] = '</blockquote>';
}
