<?php

/**
 * @file
 * Contains uipress_core.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function uipress_core_preprocess_paragraph__book_type(&$variables)
{
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $paragraph = $variables['paragraph'];
    if ($paragraph->bundle() == 'book_type') {
      if ($paragraph->field_book_sale->value == 0) {
        unset($variables['content']['field_book_sale_expiry_date'], $variables['content']['field_book_sale_price'], $variables['content']['field_book_sale_start_date'], $variables['content']['field_book_sale_code']);
      }
    }
  }
}
