adding:
  dependencies:
    config:
      - node.type.artwork
  display:
    default:
      display_options:
        pager:
          options:
            pagination_heading_level: h4
        filters:
          type:
            value:
              artwork: artwork
removing:
  display:
    default:
      display_options:
        pager:
          options:
            pagination_heading_level: h2
