<?php

/**
 * @file
 * Contains the sitenow_student_profile module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\grad_student_profile\Entity\GradStudentProfile;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function grad_student_profile_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['node']['student_profile'])) {
    $bundles['node']['student_profile']['class'] = GradStudentProfile::class;
  }
}

/**
 * Implements hook_entity_presave().
 */
function grad_student_profile_entity_presave(EntityInterface $entity): void {
  switch ($entity->bundle()) {
    case 'student_profile':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . ' ' . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_student_profile_preprocess_block__inline_block__content_list(&$variables): void {
  if (!isset($variables['attributes']['class'])) {
    $variables['attributes']['class'] = [];
  }
  $variables['attributes']['class'][] = 'list-container';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_student_profile_preprocess_field__node__student_profile(&$variables): void {
  switch ($variables['element']['#field_name']) {
    case 'field_grad_program_all_degree':
      uiowa_core_set_field_label_icon($variables, 'fas fa-graduation-cap fa-li');
      uiowa_core_set_attributes($variables, 'fa-ul');
      break;

    case 'field_person_hometown':
      uiowa_core_set_field_label_icon($variables, 'fas fa-globe-americas fa-li');
      uiowa_core_set_attributes($variables, 'fa-ul');
      break;

    case 'field_person_distinction':
      uiowa_core_set_field_icon($variables, 'fas fa-award');
      uiowa_core_set_attributes($variables, 'badge badge--primary');
      break;

    case 'field_person_bio_headline':
      uiowa_core_set_attributes($variables, 'h3 headline headline--serif');
      break;
  }
}

/**
 * Implements hook_form_alter().
 */
function grad_student_profile_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  switch ($form_id) {
    // Node form modifications.
    case 'node_student_profile_edit_form':
    case 'node_student_profile_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_student_profile_preprocess_node(&$variables): void {
  if ($variables['view_mode'] === 'card') {
    if (isset($variables['node'])) {
      $referring_item = $variables['node']->_referringItem;
      if ($referring_item) {
        /** @var \Drupal\Core\Field\EntityReferenceFieldItemList $referring_field */
        $referring_field = $referring_item->getParent();
        if ($referring_field) {
          $parent_entity = $referring_field->getParent();
          $parent_entity = $parent_entity->getEntity();
          if ($parent_entity->hasField('field_content_list_items')) {
            /** @var \Drupal\Core\Field\EntityReferenceFieldItemList $er_list */
            $er_list = $parent_entity->field_content_list_items;
            foreach ($er_list->referencedEntities() as $delta => $entity) {
              if ($variables['node']->id() === $entity->id()) {
                $variables['delta'] = $delta;
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function grad_student_profile_theme($existing, $type, $theme, $path) {
  return [
    'block_content__content_list' => [
      'template' => 'block-content--content-list',
      'base hook' => 'block_content',
    ],
    'field__node__field_person_quote' => [
      'template' => 'field--node--field-person-quote',
      'base hook' => 'field',
    ],
  ];
}
