project:
  machine_name: tippiehawkinson
  human_name: hawkinson.tippie.uiowa.edu
  local:
    hostname: tippiehawkinson.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: tippiehawkinson.prod
drupal:
  db:
    database: hawkinson_tippie_uiowa_edu
uiowa:
  requester: jkurtzleben
  site-name: 'Hawkinson Institute'
