<?php

/**
 * @file
 * Primary module hooks for uiowa.edu Core module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\Core\Render\BubbleableMetadata;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function uiowa_edu_core_form_taxonomy_term_a_z_list_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change the label of the name field.
  $form['name']['widget'][0]['value']['#title'] = t('Administrative Name');
  // Add a description to the name field.
  $form['name']['widget'][0]['value']['#description'] = t('The first character of the administrative name is used to filter the A-Z List.<br>Terms beginning with a number should be prefaced with a hash tag, example: <em>#2 Plus 2 Guaranteed Graduation Plan</em>.');
}

/**
 * Implements hook_views_pre_render().
 */
function uiowa_edu_core_views_pre_render(ViewExecutable $view) {
  // Don't override the A-Z List view title on the fixed default.
  if ($view->current_display == 'page_a_z_list' && $view->args[0] == 'a') {
    $current_path = \Drupal::service('path.current')->getPath();
    $args = explode('/', $current_path);
    if (!isset($args[2])) {
      $title = "A-Z List";
      $view->setTitle($title);
      $route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
      $route->setDefault('_title', $title);
    }
  }
}

/**
 * Implements hook_token_info().
 */
function uiowa_edu_core_token_info() {
  // Define uiowa.edu specific tokens.
  $type = [
    'name' => t('uiowa'),
    'description' => t('Custom tokens for uiowa.edu'),
  ];
  // Longer Metatag SameAs than field allows.
  $uiowa['uiowa_metatag_sameas'] = [
    'name' => t('UIowa SameAs'),
    'description' => t('uiowa.edu specific sameas values'),
  ];
  return [
    'types' => ['uiowa' => $type],
    'tokens' => ['uiowa' => $uiowa],
  ];
}

/**
 * Implements hook_tokens().
 */
function uiowa_edu_core_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  if ($type == 'uiowa') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        // Longer Metatag SameAs than field allows.
        case 'uiowa_metatag_sameas':
          $uiowa_sameas = 'https://en.wikipedia.org/wiki/University_of_Iowa,https://goo.gl/maps/vLD8h94JdRB2,https://www.facebook.com/universityofiowa,https://www.twitter.com/uiowa,https://www.instagram.com/uiowa,https://snapchat.com/add/uiowa,https://www.linkedin.com/school/university-of-iowa/,https://www.pinterest.com/uiowa,https://www.youtube.com/user/universityofiowa';
          if ($uiowa_sameas) {
            $replacements[$original] = $uiowa_sameas;
          }
          else {
            // Blank if nothing.
            $replacements[$original] = '';
          }
          break;

      }
    }
  }

  return $replacements;
}
