adding:
  dependencies:
    config:
      - field.field.media.file.field_file_archive_type
      - field.field.media.file.field_file_date_range
      - field.field.media.file.field_file_session
    module:
      - options
      - date_ap_style
  content:
    field_file_archive_type:
      type: entity_reference_label
      label: above
      settings:
        link: true
      third_party_settings: {  }
      weight: 1
      region: content
    field_file_date_range:
      type: daterange_ap_style
      label: above
      settings:
        always_display_year: 1
        use_today: 0
        cap_today: 1
        display_day: 1
        month_only: 0
        display_time: 1
        hide_date: 0
        time_before_date: 0
        display_noon_and_midnight: 0
        capitalize_noon_and_midnight: 0
        use_all_day: 0
        timezone: America/Chicago
        separator: endash
      third_party_settings: {  }
      weight: 5
      region: content
    field_file_session:
      type: list_default
      label: above
      settings: {  }
      third_party_settings: {  }
      weight: 6
      region: content
removing: {  }
