<?php

/**
 * @file
 * Article configuration for the University of Iowa.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldFilteredMarkup;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Url;
use Drupal\uiowa_core\Element\Card;
use Drupal\user\Entity\User;
use Drupal\views\Entity\View;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_entity_extra_field_info().
 */
function sitenow_articles_entity_extra_field_info() {
  $extra = [];

  $extra['node']['article'] = [
    'display' => [
      'article_created_date' => [
        'label' => t('Created Date'),
        'description' => t('Date the node was created.'),
        'weight' => 100,
        'visible' => TRUE,
      ],
    ],
  ];

  return $extra;
}

/**
 * Implements hook_form_alter().
 */
function sitenow_articles_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_article_edit_form':
      if (isset($form['field_article_preserve_links'])) {
        // Set description message to only display when the user doesn't have
        // the 'administer sitenow articles' permission.
        $user = User::load(\Drupal::currentUser()->id());
        if ($user->hasPermission('administer sitenow articles')) {
          $form['field_article_preserve_links']['widget']['value']['#description'] = FieldFilteredMarkup::create($form['field_article_preserve_links']['widget']['value']['#description'] . ' <a href="/admin/config/sitenow/uiowa-articles" target="_blank" rel="noopener">Customize this message and other site-wide article settings.</a>');
        }
      }
    case 'node_article_form':
      if (isset($form['field_related_content'])) {
        // Set field_related_content to node_reference group.
        $form['field_related_content']['#group'] = 'node_relations';
      }
      $form['field_article_source_link_direct']['#states'] = [
        'visible' => [
          ':input[name="field_article_source_link[0][uri]"]' => ['filled' => TRUE],
        ],
      ];
      // If article is being created, hide the preserve links checkbox.
      if ($form_id === 'node_article_form') {
        $form['field_article_preserve_links']['#access'] = FALSE;
      }

      // If a new person is being created for the contact field,
      // they don't have a "title" yet, and so we need to fetch
      // their first and last names and combine in order to display.
      // Check that there are entities.
      if (isset($form['field_contact_reference']['widget']['entities'])) {
        $contacts = $form['field_contact_reference']['widget']['entities'];

        // For each one that exists, make sre it is one of the integer entries,
        // which is actually an entity.
        foreach ($contacts as $key => $contact) {
          if (is_int($key) && $contact['#entity']->getType() === 'person') {

            // Then, get the string of the first and last names.
            $first = $contact['#entity']?->get('field_person_first_name')?->getString();
            $last = $contact['#entity']?->get('field_person_last_name')?->getString();

            // And set the title, which would have been empty,
            // to the concatenation of the two.
            if (is_string($first) && is_string($last)) {
              $form['field_contact_reference']['widget']['entities'][$key]['#label'] = $first . ' ' . $last;
            }
          }
        }
      }
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_articles_form_views_ui_edit_display_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['options']['link_url']['#description'][2]['#markup'] = ' {{ sitenow_articles.path }} is the SiteNow Articles path setting.';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_breadcrumb(&$variables) {
  // Not ideal. Unset view contextual filter breadcrumb duplicates.
  // Waiting for https://www.drupal.org/project/drupal/issues/2966004,
  // https://www.drupal.org/project/drupal/issues/2787051...
  $routes = [];
  foreach ($variables["links"] as $key => $link) {
    $url = $link->getURL();
    // Test for external paths.
    if ($url->isRouted()) {
      $routes[$key] = $link->getUrl()->getRouteName();
    }
  }
  // For breadcrumb links built from view articles path, reduce duplicates.
  if (in_array('view.articles.page_articles', $routes)) {
    $unique_routes = array_keys(array_unique($routes, SORT_REGULAR));
    foreach ($variables["breadcrumb"] as $key => $value) {
      if (!in_array($key, $unique_routes)) {
        unset($variables["breadcrumb"][$key]);
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] === 'field_article_author') {
    if ($variables['element']['#formatter'] === 'entity_reference_label') {
      $variables['element']["#title"] = 'Written by';
      $variables["label"] = 'Written by';
    }
    // Loop through all author fields in the byline and add credentials
    // (if available) to their names.
    foreach ($variables['items'] as $key => $item) {
      $author_entity = $item['content']['#options']['entity'];
      $credentials = $author_entity
        ?->field_person_credential
        ?->value;

      if (!is_null($credentials)) {
        $variables['items'][$key]['content']['#title'] .= ', ' . $credentials;
      }
    }
  }
  if ($variables['element']['#field_name'] === 'field_article_source_org') {
    if ($variables['element']['#formatter'] === 'string') {
      $variables['element']["#title"] = 'Organization';
      $variables["label"] = 'Organization';
    }
  }
  if ($variables['element']['#field_name'] === 'field_article_source_link') {
    if ($variables['element']['#formatter'] === 'link') {
      $variables['element']["#title"] = 'Source';
      $variables["label"] = 'Source';
    }
  }
  if ($variables['element']['#field_name'] === 'field_image_caption') {
    $variables["attributes"]['class'][] = 'figure-caption';
    $variables["attributes"]['id'] = 'node-caption';
  }
  if ($variables['element']['#field_name'] === 'field_image') {
    $node = $variables['element']['#object'];
    if ($node->hasField('field_image_caption') && !$node->get('field_image_caption')->isEmpty()) {
      $variables["attributes"]['aria-describedby'] = 'node-caption';
    }
  }
  if ($variables['element']['#field_name'] === 'field_related_content') {
    $variables['attributes']['class'][] = 'inner--grid';
    $variables['attributes']['class'][] = 'grid--threecol--33-34-33';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function sitenow_articles_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  if ($variables['element']['#field_name'] === 'field_article_author') {
    if ($variables['element']['#formatter'] === 'entity_reference_label') {
      $suggestions[] = 'field__node__field_article_author__sep';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_page(&$variables) {
  $current_route = \Drupal::routeMatch();
  $route_name = $current_route->getRouteName();
  if ($route_name === 'view.articles.page_articles') {
    // Get the current user.
    $user = \Drupal::currentUser();
    // Check for permission.
    if ($user->hasPermission('administer sitenow articles') === TRUE) {
      // Print warning message informing user to use basic site settings.
      $url = Url::fromRoute('sitenow_articles.settings_form');
      $settings_link = Link::fromTextAndUrl(t('SiteNow Articles'), $url)
        ->toString();
      $message_text = t('This page can be configured here: @settings_link', [
        '@settings_link' => $settings_link,
      ]);
      \Drupal::messenger()->addStatus($message_text);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_node(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {

    $node = $variables['node'];
    switch ($node->getType()) {
      case 'article':
        $variables['content']['article_author'] = $node->field_article_author->view([
          'type' => 'entity_reference_label',
          'label' => 'inline',
          'settings' => [],
        ]);
        if (!$node->get('field_article_source_org')->isEmpty() && !$node->get('field_article_source_link')->isEmpty()) {
          $variables['content']['field_article_source_link'][0]['#title'] = $node->field_article_source_org->value;
          switch ($variables['view_mode']) {
            case 'teaser':
              // Unset source link if directly linking out to prevent
              // redundant links.
              if ($node->hasField('field_article_source_link_direct')) {
                if ((int) $node->field_article_source_link_direct->value === 1 && !$node->get('field_article_source_link')->isEmpty()) {
                  unset($variables['content']['field_article_source_link']);
                }
                else {
                  unset($variables['content']['field_article_source_org']);
                }
              }
              break;

            case 'full':
            case 'default':
              unset($variables['content']['field_article_source_org']);
              break;

          }
        }
        if ($variables['view_mode'] === 'teaser') {
          // Heading needs to change based on placement. Defaults to h3 in twig.
          $current_route = \Drupal::routeMatch();
          $route_name = $current_route->getRouteName();
          $variables['#cache']['contexts'][] = 'route.name';
          if (str_starts_with($route_name, 'view.articles.')) {
            $variables['heading_size'] = 'h2';
          }

          if ($node->hasField('field_article_source_link_direct')) {
            if ((int) $node->field_article_source_link_direct->value === 1 && !$node->get('field_article_source_link')->isEmpty()) {
              unset($variables['content']['field_article_source_link']);
            }
          }
        }
        if (in_array($variables['view_mode'], ['default', 'full'])) {
          // Check if we don't have any gallery images.
          if ($node->hasField('field_gallery_images') &&
            empty($node->get('field_gallery_images')->getValue())) {
            // Loop through our article layout blocks and look for
            // the gallery jump link block (defined by this module).
            // We expect it to be the last block in most cases,
            // so we iterate in reverse.
            foreach (array_reverse($variables['content']['_layout_builder'][1]['content'], TRUE) as $key => $block) {
              if (isset($block['#plugin_id']) && $block['#plugin_id'] === 'galleryjumplink_block') {
                unset($variables['content']['_layout_builder'][1]['content'][$key]);
                // There should only be one instance of the jump link,
                // so if we've already unset it, finish the loop.
                break;
              }
            }
          }

          if ($node->hasField('field_article_preserve_links')) {
            // Check if preserve links checkbox is checked.
            if ((int) filter_var($node->field_article_preserve_links->value, FILTER_VALIDATE_BOOLEAN) !== 1) {
              // If it isn't checked, hide the broken links message.
              foreach (array_reverse($variables['content']['_layout_builder'][1]['content'], TRUE) as $key => $block) {
                if (isset($block['#plugin_id']) && $block['#plugin_id'] == 'preservedlinksmessage_block') {
                  unset($variables['content']['_layout_builder'][1]['content'][$key]);
                  break;
                }
              }
            }
          }
        }
        break;

    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function sitenow_articles_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  switch ($entity->getType()) {
    case 'article':
      if ($display->getComponent('article_created_date')) {
        $created = $entity->get('created')->value;
        $date = \Drupal::service('date.formatter')->format($created, 'medium');
        $build['article_created_date'] = [
          '#type' => 'markup',
          '#markup' => '<span class="article-created-date">' . $date . '</span>',
        ];
      }
      if ($view_mode === 'teaser') {
        $mapping = [
          '#media' => 'field_image',
          '#title' => 'title',
          '#content' => 'field_teaser',
        ];

        $build = uiowa_core_node_view_build_card($build, $entity, $mapping);
      }
      break;

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_views_view(&$variables) {
  switch ($variables['id']) {
    case 'articles':
      /** @var  \Drupal\views\ViewExecutable $view */
      $view = $variables['view'];

      if (empty($variables['header']['area']['#text'])) {
        unset($variables['header']['area']);
      }

      // If this is the page display and arguments were provided, hide the
      // feed icons since we don't want to promote those filtered RSS feeds.
      if ($view->current_display === 'page_articles' && !empty($view->args)) {
        $variables['feed_icons'] = [];
      }

      break;

  }
}

/**
 * Implements hook_preprocess_views_view_summary().
 */
function sitenow_articles_preprocess_views_view_summary(&$variables) {
  if ($variables['view']->current_display === 'block_articles_archive') {
    foreach ($variables['rows'] as $row) {
      $explode = explode('/', $row->url);
      unset($explode[3]);
      $explode[2] = substr_replace($explode[2], '/', 4, 0);
      $row->url = implode("/", $explode);
    }
  }
}

/**
 * Implements hook_preprocess_views_view_unformatted().
 */
function sitenow_articles_preprocess_views_view_unformatted(&$variables) {
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  if ($view->id() === 'article_list_block') {
    $rows = $variables['rows'];
    $style = $view->style_plugin;

    foreach ($rows as $id => $row) {
      // Need to get these values regardless of whether they are hidden or not.
      $link_direct = (int) $row['content']['#node']->get('field_article_source_link_direct')->value;
      $source_link = $row['content']['#node']->get('field_article_source_link')->uri;
      $org = $row['content']['#node']->get('field_article_source_org')->value;
      $nid = $row['content']['#node']->get('nid')->value;

      // If source link is set and link direct is checked, set $card_link_url to
      // source link. Otherwise, $card_link_url should be set to node link.
      if ($link_direct === 1
        && isset($source_link) && !empty($source_link)) {
        $card_link_url = $source_link;
      }
      else {
        $card_link_url = \Drupal::service('path_alias.manager')->getAliasByPath('/node/' . $nid);
      }

      $card_tag = [
        '#type' => 'html_tag',
        '#tag' => 'span',
        '#attributes' => [
          'class' => [
            'field--name-field-article-source-link',
          ],
        ],
      ];
      if ($org && $style->getField($id, 'field_article_source_org')) {
        $org = $style->getField($id, 'field_article_source_org');
        // If source link is hidden...
        if ($style->getField($id, 'field_article_source_link') === NULL) {
          // But source_link has value...
          if ($source_link) {
            // Wrap org in the source link.
            $org = Link::fromTextAndUrl($style->getField($id, 'field_article_source_org'), Url::fromUri($source_link))
              ->toString();
          }
        }

        $card_tag['org'] = [
          '#prefix' => '<span class="views-field-article-source-link">',
          '#markup' => $org,
          '#suffix' => '</span>',
        ];
      }
      if ($source_link && $style->getField($id, 'field_article_source_link')) {
        $card_tag['source_link'] = [
          '#prefix' => '<span class="views-field-article-source-link">',
          '#markup' => $style->getField($id, 'field_article_source_link'),
          '#suffix' => '</span>',
        ];
      }

      $variables['rows'][$id]['content']['#url'] = $card_link_url;
      $variables['rows'][$id]['content']['#subtitle'] = $style->getField($id, 'created');
      $variables['rows'][$id]['content']['#meta']['tag'] = $card_tag;
      $variables['rows'][$id]['content']['#meta']['field_article_author']['#markup'] = $style->getField($id, 'field_article_author');
    }
  }
}

/**
 * Implements hook_uip_classes_alter().
 */
function sitenow_articles_uip_classes_alter(&$options, $entity, $bundle) {
  switch ($bundle) {
    case 'articles':
      $options['hide-descriptions'] = 'Hide Summaries';
      $options['hide-images'] = 'Hide Images';
      $options['grid'] = 'Grid';
      $options['masonry'] = 'Masonry';
      break;

  }
}

/**
 * Implements hook_theme().
 */
function sitenow_articles_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__articles__default' => [
      'template' => 'paragraph--articles--default',
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_paragraph(&$variables) {
  $paragraph = $variables['paragraph'];
  switch ($paragraph->bundle()) {
    case 'articles':
      $admin_context = \Drupal::service('router.admin_context');
      if (!$admin_context->isAdminRoute()) {

        // Display title if it exists.
        if ($paragraph->hasField('field_uip_display_title')) {
          if ((int) $paragraph->field_uip_display_title->value === 1) {
            $variables['display_title'] = TRUE;
          }
        }

        if ($paragraph->hasField('field_uip_classes') && !$paragraph->get('field_uip_classes')->isEmpty()) {
          $classes = $paragraph->get('field_uip_classes')->getValue();
          // Clean array of classes selected.
          $classes = array_column($classes, 'value');
          // Check for grid classes otherwise add list class.
          $display_options = [
            'grid',
            'masonry',
          ];
          $result = array_intersect($display_options, $classes);
          if (!$result) {
            $variables['attributes']['class'][] = 'list';
          }
        }
        else {
          $variables['attributes']['class'][] = 'list';
        }
        // Get field_uip_colwidth value.
        if ($paragraph->hasField('field_uip_colwidth')) {
          $variables['attributes']['class'][] = $paragraph->field_uip_colwidth->value;
        }
        // Get field_uip_id value.
        if ($paragraph->hasField('field_uip_id')) {
          $variables['attributes']['id'][] = Html::getClass($paragraph->field_uip_id->value);
        }

        $view = Views::getView('articles_block');
        $view->setDisplay('block_articles');
        $view->display_handler->setOption('parent_entity', $paragraph);

        if ($paragraph->hasField('field_reference') && !$paragraph->get('field_reference')->isEmpty()) {
          $tids = $paragraph->get('field_reference')->getValue();
          // Clean array of tids selected.
          $tids = array_column($tids, 'target_id');
        }
        else {
          $tids = ['all'];
        }
        // Contextual relationship filter.
        $args = implode('+', $tids);
        $view->setArguments([$args]);

        if ($paragraph->hasField('field_uip_items') && !$paragraph->get('field_uip_items')->isEmpty()) {
          $items = $paragraph->field_uip_items->value;
          $view->setItemsPerPage($items);
          $view->setExposedInput([
            'items_per_page' => $items,
          ]);
        }
        $pager_type = 'some';
        // Show pager if it exists and is set.
        if ($paragraph->hasField('field_uip_pager')) {
          if ((int) $paragraph->field_uip_pager->value === 1) {
            $pager_type = 'full';
          }
        }

        $pager = $view->display_handler->getOption('pager');
        // IF show pager, change pager_type to 'full'.
        $pager['type'] = $pager_type;
        $view->display_handler->setOption('pager', $pager);

        $view->preExecute();
        $view->execute();
        $variables['content']['view'] = $view->render();

        // If we have more link checked and link provided, pass it.
        if ($paragraph->hasField('field_articles_more')) {
          $more = (int) $paragraph->field_articles_more->value === 1;
          if ($more === TRUE) {
            $variables['more'] = [
              '#type' => 'container',
              '#attributes' => [
                'class' => 'more-link',
              ],
            ];

            $view = View::load('articles');
            $default =& $view->getDisplay('default');

            if (!empty($more_path = $paragraph->get('field_articles_more_path')->getValue())) {
              $url = Url::fromUri($more_path[0]['uri']);
            }
            elseif ($view->getDisplay('page_articles')['display_options']['enabled'] === TRUE) {
              $url = Url::fromRoute('view.articles.page_articles');
            }
            if (isset($url)) {
              $variables['more']['btn'] = [
                '#type' => 'link',
                '#title' => 'View more ' . strtolower($default['display_options']['title']),
                '#url' => $url,
                '#attributes' => [
                  'class' => ['btn', 'btn-primary'],
                ],
              ];
            }
          }
        }
      }

      break;
  }
}

/**
 * Implements hook_views_pre_render().
 */
function sitenow_articles_views_pre_render(ViewExecutable $view) {
  // Add replacement token for articles page path.
  $view->build_info['substitutions']['{{ sitenow_articles.path }}'] = _sitenow_articles_path_token_value();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_articles_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $view = $form_state->get('view');
  if ($view->id() === 'articles_block') {
    if ($view->current_display === 'block_articles') {
      $exposed_input = $view->getExposedInput();
      if (isset($exposed_input["items_per_page"])) {
        $form["items_per_page"]["#options"] = [$exposed_input["items_per_page"] => $exposed_input["items_per_page"]];
        $form["#attributes"]["class"][] = 'hidden';
      }
    }
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 */
function sitenow_articles_field_widget_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element["#paragraph_type"] === 'articles') {
    if (!empty($element['subform']['field_articles_more'])) {
      $parents_array = $element['subform']['#parents'];
      $parents = array_shift($parents_array) . '[' . implode('][', $parents_array) . ']';
      if (!empty($element['subform']['field_articles_more_path'])) {
        $element['subform']['field_articles_more_path']['#states'] = [
          'visible' => [
            ':input[name="' . $parents . '[field_articles_more][value]"]' => [
              'checked' => TRUE,
            ],
          ],
        ];
      }
    }
  }
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function sitenow_articles_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['field_name'] === 'field_contact_reference') {
    // Clean up, minimize the person IEF form.
    if (in_array('person', $context['allowed_bundles'])) {
      $fields['label']['label'] = t('Contact name');
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_articles_preprocess_block(&$variables) {
  switch ($variables['elements']['#plugin_id']) {
    case 'views_block:article_list_block-list_article':
      if (isset($variables['attributes']['class'])) {
        // Unset classes meant for children.
        foreach ($variables['attributes']['class'] as $key => $style) {
          foreach ([
            'bg',
            'card',
            'media',
            'hide',
          ] as $check) {
            if (substr($style, 0, strlen($check)) === $check) {
              unset($variables['attributes']['class'][$key]);
            }
          }
        }
      }

      break;

    // @todo Move this to a more appropriate spot, if we may
    //   want to use the gallery image field for other content.
    case 'field_block:node:article:field_gallery_images':
      $variables['attributes']['class'][] = 'grid--fivecol--20';
      $variables['attributes']['class'][] = 'photoswipe-gallery';

      break;

    case 'field_block:node:article:field_article_author':
    case 'field_block:node:article:field_article_source_link':
    case 'field_block:node:article:field_article_source_org':
    case 'galleryjumplink_block':
    case 'field_block:node:article:field_image_caption':
      $variables['attributes']['class'][] = 'article--meta';

      break;

    case 'field_block:node:article:field_contact_reference':
      $variables['attributes']['class'][] = 'article--meta article--meta__block';

      break;
  }
}

/**
 * Implements hook_token_info().
 */
function sitenow_articles_token_info(): array {
  $info = [];
  $info['types']['sitenow_articles'] = [
    'name' => t('SiteNow Articles'),
    'description' => t('Tokens for SiteNow Articles.'),
  ];
  $info['tokens']['sitenow_articles']['path'] = [
    'name' => 'SiteNow Articles path',
    'description' => 'A token to display the SiteNow Articles page path.',
  ];
  return $info;
}

/**
 * Implements hook_tokens().
 */
function sitenow_articles_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];
  if ($type === 'sitenow_articles') {

    foreach ($tokens as $name => $original) {
      // Find the desired token by name.
      switch ($name) {
        case 'sitenow_articles_path':
          $replacements[$original] = _sitenow_articles_path_token_value();
          break;
      }
    }
  }
  return $replacements;
}

/**
 * Callback to get the SiteNow Articles view path.
 */
function _sitenow_articles_path_token_value() {

  // Load articles listing view.
  $view = Drupal::entityTypeManager()->getStorage('view')->load('articles');

  // Loop through displays except Master.
  $displays = $view->get('display');
  unset($displays['default']);
  foreach ($displays as $display_id => $display) {
    // If page display is not enabled, skip.
    if ($display_id !== 'page_articles') {
      continue;
    }

    // @todo Do we need to do anything besides this?
    return '/' . $display['display_options']['path'];
  }

  // @todo Is this appropriate when there is no value?
  return '';
}

/**
 * Implements hook_ENTITY_TYPE_build_defaults_alter().
 */
function sitenow_articles_node_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  if ($entity->bundle() === 'article' && $view_mode === 'teaser') {
    $build['#type'] = 'card';
    unset($build['#theme']);
    $build['#pre_render'] = [
      [
        Card::class,
        'preRenderCard',
      ],
    ];
  }
}
