<?php

/**
 * @file
 * Primary module hooks for wellbeing_core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function wellbeing_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-page-list-block-list-page') {
    $form['#attached']['library'][] = 'sitenow/chosen';
  }
}
