adding:
  dependencies:
    config:
      - node.type.thesis_defense
  permissions:
    - 'delete thesis_defense revisions'
    - 'edit any thesis_defense content'
    - 'edit own thesis_defense content'
    - 'override thesis_defense published option'
    - 'revert thesis_defense revisions'
removing: {  }
