<?php

/**
 * @file
 * Functions to support theming in the Iowa Superfund theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function iowasuperfund_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function iowasuperfund_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function iowasuperfund_preprocess_node(&$variables) {

}
