<?php

/**
 * @file
 * Contains install and update routines for Media Core.
 */
use Drupal\filter\Entity\FilterFormat;

/**
 * Implements hook_install().
 */
function media_core_install() {
  user_role_grant_permissions('anonymous', ['view media']);
  user_role_grant_permissions('authenticated', ['view media']);

  $filter = FilterFormat::load('rich_text');
  $filter->set('weight', -10);
  $filter->save();
}