<?php

/**
 * @file
 * Provides a basic news content type for standard sites.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function basic_types_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.basic_types_news':
      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      else {
        $filepath = dirname(__FILE__) . '/README.txt';
        if (file_exists($filepath)) {
          $readme = file_get_contents($filepath);
        }
      }
      if (!isset($readme)) {
        return NULL;
      }

      /* @var \Drupal\Core\Extension\ModuleHandler $moduleHandler*/
      $moduleHandler = \Drupal::service('module_handler');
      if ($moduleHandler->moduleExists('markdown')) {
        $filters = $moduleHandler->invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];

        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_page_attachments().
 */
function basic_types_news_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'basic_types_news/basic_types_news_styling';
}

/**
 * Implements hook_theme().
 */
function basic_types_news_theme(array $variables) {
  $theme = [];

  $theme['node__news'] = [
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--news',
    'path' => drupal_get_path('module', 'basic_types_news') . '/templates',
  ];

  $theme['node__news__teaser'] = [
    'render element' => 'content',
    'base hook' => 'node',
    'template' => 'node--news--teaser',
    'path' => drupal_get_path('module', 'basic_types_news') . '/templates',
  ];

  return $theme;
}
