<?php

/**
 * @file
 * Primary module hooks for uiowa_aggregator module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uiowa_aggregator_form_aggregator_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var Drupal\uiowa_core\Access\UiowaCoreAccess $check */
  $check = \Drupal::service('uiowa_core.access_checker');

  /** @var Drupal\Core\Access\AccessResultInterface $is_admin */
  $access = $check->access(\Drupal::currentUser()->getAccount());

  if ($access->isForbidden()) {
    $form['aggregator_allowed_html_tags']['#disabled'] = TRUE;
    $form['aggregator_allowed_html_tags']['#description'] .= t(' <em>This field has been disabled for security reasons.</em>');

    // Remove one hour and never from aggregator cleanup options since cron runs every three hours.
    unset($form['processors']['aggregator']['aggregator_clear']['#options'][3600]);
    unset($form['processors']['aggregator']['aggregator_clear']['#options'][0]);
    $form['processors']['aggregator']['aggregator_clear']['#description'] = t('<em>Items cannot be kept indefinitely for performance reasons.</em>');
  }
}
