<?php

/**
 * @file
 * Update hooks for uiowa_aggregator.
 */

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Add a new field to aggregator_form.
 */
function uiowa_aggregator_update_10001() {
  $storage_definition = BaseFieldDefinition::create('boolean')
    ->setDefaultValue(FALSE);
  $update_manager = \Drupal::entityDefinitionUpdateManager();
  $update_manager->installFieldStorageDefinition('purge_items', 'aggregator_feed', 'aggregator', $storage_definition);
}
