<?php

/**
 * @file
 * Contains grad_srop.module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_entity_presave().
 */
function grad_custom_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'thesis_defense':
    case 'scholar':
    case 'mentor':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . " " . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}
/**
 * Implements hook_preprocess_HOOK().
 */
function grad_custom_preprocess_page_title(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    if ($route_name == 'entity.node.canonical') {
      $node = \Drupal::routeMatch()->getParameter('node');
    }
    elseif ($route_name == 'entity.node.preview') {
      $node = \Drupal::routeMatch()->getParameter('node_preview');
    }
    if (isset($node)) {
      switch ($node->getType()) {
        case 'scholar':
        case 'mentor':
          if ($node->hasField('field_person_credential') && !$node->get('field_person_credential')
            ->isEmpty()) {
            $variables['subtitle'] = $node->field_person_credential->value;
          }
          break;
      }
    }
  }
}

/**
 * Implements hook_theme for templates.
 */
function grad_custom_theme($existing, $type, $theme, $path) {
  return [
    'field__node__field_scholar_mentor' => [
      'template' => 'field--node--field-scholar-mentor',
      'base hook' => 'field',
    ],
    'field__node__field_person_research_assistants' => [
      'template' => 'field--node--field-person-research-assistants',
      'base hook' => 'field',
    ],
    'field__node__field_scholar_participation_year' => [
      'template' => 'field--node--field-scholar-participation-year',
      'base hook' => 'field',
    ],
    'node__view__srop_scholars' => [
      'template' => 'node--view--srop-scholars',
      'base hook' => 'node',
    ],
    'node__mentor__full' => [
      'template' => 'node--mentor--full',
      'base hook' => 'node',
    ],
    'node__scholar__full' => [
      'template' => 'node--scholar--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function grad_custom_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_thesis_defense_edit_form':
    case 'node_thesis_defense_form':
      // Our submit handler must execute before the layout_builder_styles one
      // so it can take advantage of the logic there.
      array_unshift($form['actions']['submit']['#submit'], '_grad_custom_thesis_defense_submit');
      if (isset($form['field_thesis_defense_date'])) {
        $form['field_thesis_defense_date']['widget'][0]['end_value']['#access'] = FALSE;
        $form['field_thesis_defense_date']['widget'][0]['duration']['#access'] = FALSE;
      }
      break;
  }
}

/**
 * Custom form submit function for thesis_defense.
 *
 * If the start and end date don't match, set them to the same value.
 *
 * @param array $form
 *   The form element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function _grad_custom_thesis_defense_submit(array &$form, FormStateInterface $form_state) {
  if ($date_field = $form_state->getValue(['field_thesis_defense_date', 0])) {
    $start = $date_field['value'];
    $end = $date_field['end_value'];

    // If these values don't match, make them match.
    if ($end->getPhpDateTime() != $start->getPhpDateTime()) {
      $form_state->setValue(['field_thesis_defense_date', 0, 'end_value'], $start);
    }
  }
}

/**
 * Implements hook_allowed_values_function().
 */
function grad_disciplines_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  return [
    'Applied Health Sciences' => 'Applied Health Sciences',
    'Biomedical and Life Sciences' => 'Biomedical and Life Sciences',
    'Engineering' => 'Engineering',
    'Education' => 'Education',
    'Humanities' => 'Humanities',
    'Physical Sciences' => 'Physical Sciences',
    'Social Sciences' => 'Social Sciences',
  ];
}

/**
 * Implements hook_allowed_values_function().
 */
function grad_degrees_offered_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  return [
    'Au.D.' => 'Au.D.',
    'Certificate' => 'Certificate',
    'D.M.A.' => 'D.M.A.',
    'D.N.P.' => 'D.N.P.',
    'D.P.T.' => 'D.P.T.',
    'Ed.S.' => 'Ed.S.',
    'Ed.S.nt' => 'Ed.S.<sup>1</sup>',
    'Ed.D.nt' => 'Ed.D.<sup>1</sup>',
    'M.A.' => 'M.A.',
    'M.A.ses' => 'M.A.<sup>4</sup>',
    'M.A.tnt' => 'M.A.<sup>*</sup>',
    'M.A.tnt.ses' => 'M.A.<sup>*</sup><sup>2</sup>',
    'M.A.nt' => 'M.A.<sup>1</sup>',
    'M.A.T.' => 'M.A.T.',
    'M.A.T.nt' => 'M.A.T.<sup>1</sup>',
    'M.A.T.ses' => 'M.A.T.<sup>2</sup>',
    'M.A.T.nt.ses' => 'M.A.T.<sup>1,2</sup>',
    'M.Ac.' => 'M.Ac.<sup>1</sup>',
    'M.B.A.' => 'M.B.A.',
    'M.C.S.' => 'M.C.S.',
    'M.C.S.nt' => 'M.C.S.<sup>1</sup>',
    'M.D.' => 'M.D.',
    'M.F.A.' => 'M.F.A.',
    'M.H.A.' => 'M.H.A.',
    'M.H.A.nt' => 'M.H.A.<sup>1</sup>',
    'M.P.H.' => 'M.P.H.',
    'M.P.H.nt' => 'M.P.H.<sup>1</sup>',
    'M.S.' => 'M.S.',
    'M.S.ses' => 'M.S.<sup>2</sup>',
    'M.S.tnt' => 'M.S.<sup>*</sup>',
    'M.S.tnt.ses' => 'M.S.<sup>*</sup><sup>2</sup>',
    'M.S.nt' => 'M.S.<sup>1</sup>',
    'M.S.N.' => 'M.S.N.',
    'M.S.N.tnt' => 'M.S.N.<sup>*</sup>',
    'M.S.W.' => 'M.S.W.',
    'M.S.W.tnt' => 'M.S.W.<sup>*</sup>',
    'Ph.D.' => 'Ph.D.',
    'Ph.D.ses' => 'Ph.D.<sup>2</sup>',
    'Ph.D.bio' => 'Ph.D.<sup>3</sup>',
    'NoDegree' => 'Not a degree major',
    'NoDegree3' => 'Not a degree major<sup>3</sup>',
  ];
}

/**
 * Implements hook_allowed_values_function().
 */
function grad_programs_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  return [
    'ACTG' => "Accounting",
    'ACT_SCI' => "Actuarial Science",
    'ADULT_GER_NP_ACUTE_CARE' => "Adult Gerontology Acute Care Nurse Practitioner",
    'ADULT_GER_NP_PRM_CARE' => "Adult Gerontology Primary Care Nurse Practitioner",
    'AFR_AM' => "African American Studies",
    'AFR_AM_WORLD' => "African American World Studies",
    'AGING' => "Aging and Longevity Studies",
    'AGRI_SAF_HLTH' => "Agricultural Safety and Health",
    'AM_IND_NAT' => "Native American and Indigenous Studies",
    'AM_STDS:SP_AMER_ST_SPRT_ST' => "American Studies - Sport Studies",
    'AM_STDS' => "American Studies",
    'ANAT_CELL_BIOL' => "Anatomy and Cell Biology",
    'ANTH' => "Anthropology",
    'APPL_MATH_CS' => "Applied Mathematical and Computational Sciences",
    'APP_BEHAV_ANALYSIS' => "Applied Behavior Analysis",
    'ART' => "Art",
    'ART_HIST' => "Art History",
    'ASIAN_CIV' => "Asian Civilizations",
    'ASTR' => "Astronomy",
    'ATHLETIC_TRNG' => "Athletic Training",
    'BIOCHEM' => "Biochemistry",
    'BIOMED_ENGR' => "Biomedical Engineering",
    'BIOMED_SCI_GRAD:SP_CANCER_BIOL' => "Biomedical Science - Cancer Biology",
    'BIOMED_SCI_GRAD:SP_CELL_DEV_BIOL' => "Biomedical Science - Cell and Developmental Biology",
    'BIOMED_SCI_GRAD:SP_EXPER_PATH' => "Biomedical Science - Experimental Pathology",
    'BIOMED_SCI_GRAD:SP_FREE_RAD_RADIAT_BIOL' => "Biomedical Science - Free Radical and Radiation Biology",
    'BIOMED_SCI_GRAD:SP_MOLEC_CELL_BIOL' => "Biomedical Science - Molecular Medicine",
    'BIOMED_SCI_GRAD:SP_MOLEC_PHYS_BIOPHYS' => "Biomedical Science - Molecular Physiology and Biophysics",
    'BIOMED_SCI_GRAD:SP_PHARMACOL' => "Biomedical Science - Pharmacology",
    'BIOMED_SCI_GRAD' => "Biomedical Science",
    'BIO_STAT' => "Biostatistics",
    'BKST_BKART' => "Book Studies/Book Arts and Technologies",
    'BOOK_ARTS' => "Book Arts",
    'BUSN:SP_ACTG' => "Business Administration - Accounting",
    'BUSN:SP_FINANCE' => "Business Administration - Finance",
    'BUSN:SP_MGMT_ORGS' => "Business Administration - Management",
    'BUSN:SP_MGMT_SCI' => "Business Administration - Business Analytics",
    'BUSN:SP_MKTG' => "Business Administration - Marketing",
    'BUSN' => "Business Administration",
    'BUSN_ANALYTICS:SP_CAREER' => "Business Analytics - Career",
    'BUSN_ANALYTICS:SP_PROFESSIONAL' => "Business Analytics - Professional",
    'BUSN_ANALYTICS' => "Business Analytics",
    'CHEM' => "Chemistry",
    'CHEM_BIO_ENGR' => "Chemical and Biochemical Engineering",
    'CIV_ENV_ENGR:SP_ENV_ENGR' => "Civil and Environmental Engineering - Environmental Engineering",
    'CIV_ENV_ENGR:SP_ENV_SCI' => "Civil and Environmental Engineering - Environmental Science",
    'CIV_ENV_ENGR:SP_HYD' => "Civil and Environmental Engineering - Hydraulics",
    'CIV_ENV_ENGR:SP_STRUCT_MECH_MTLS' => "Civil and Environmental Engineering - Structures, Mechanics and Materials",
    'CIV_ENV_ENGR:SP_SUSTAIN_WATER_DEV' => "Civil and Environmental Engineering - Sustainable Water Development",
    'CIV_ENV_ENGR:SP_TRANSP' => "Civil and Environmental Engineering - Transportation",
    'CIV_ENV_ENGR:SP_WTR_RES' => "Civil and Environmental Engineering - Water Resources",
    'CIV_ENV_ENGR' => "Civil and Environmental Engineering",
    'CLASSICS' => "Classics",
    'CLIN_INV_GRAD' => "Clinical Investigation",
    'COGNITIVE_SCI_LANG' => "Cognitive Science of Language",
    'COLL_TCH:ct_biol_lifesci' => "College Teaching - Biological/Life Sciences",
    'COLL_TCH:ct_fineart_hum' => "College Teaching - Fine Arts and Humanities",
    'COLL_TCH:ct_phys_mathsci' => "College Teaching - Physical and Mathematical Sciences",
    'COLL_TCH:ct_soc_sci' => "College Teaching - Social Sciences",
    'COLL_TCH' => "College Teaching",
    'COMM:SP_COMM_RSRCH' => "Communication Studies - Communication Research",
    'COMM:SP_RHET_ST' => "Communication Studies - Rhetorical Studies",
    'COMM' => "Communication Studies",
    'COMM_BEH_HLTH' => "Community and Behavioral Health",
    'COMP_SCI:SP_CS_SFTW_ENG' => "Computer Science - Software Engineering",
    'COMP_SCI' => "Computer Science",
    'CRSD:SP_CLIN_MENTAL_HLTH_COUNS' => "Rehabilitation and Counselor Education - Clinical Mental Health Counseling",
    'CRSD:SP_C_EDUC_SPRV' => "Rehabilitation and Counselor Education - Counselor Education and Supervision",
    'CRSD:SP_REHAB_COUNS_PROG' => "Rehabilitation and Counselor Education - Rehabilitation Counseling Program",
    'CRSD:SP_REHAB_PSYCH' => "Rehabilitation and Counselor Education - Rehabilitation Psychology",
    'CRSD:SP_SCHL_C' => "Rehabilitation and Counselor Education - School Counseling",
    'CRSD:SP_ST_AFF_ADM_REA' => "Rehabilitation and Counselor Education - Student Affairs Administration and Research",
    'CRSD:SP_ST_DEV_PSE' => "Rehabilitation and Counselor Education - Student Development in Postsecondary Education",
    'CRSD' => "Rehabilitation and Counselor Education",
    'DANCE' => "Dance",
    'DENT_PH' => "Dental Public Health",
    'DIET_INTERN' => "Dietetic Internship Program",
    'DIGITAL_PUBLIC_HUMANITIES' => "Public Digital Humanities",
    'ECON' => "Economics",
    'EDUC_PLS:SP_EDUC_LDRSHIP' => "Educational Policy and Leadership Studies - Educational Leadership",
    'EDUC_PLS:SP_HIGHER_ED' => "Educational Policy and Leadership Studies - Higher Education and Student Affairs",
    'EDUC_PLS:SP_HIGHER_EDUC' => "Educational Policy and Leadership Studies - Higher Education",
    'EDUC_PLS:SP_PK12_ADMIN' => "Educational Policy and Leadership Studies - PK-12 Administration",
    'EDUC_PLS:SP_SCHL_CURR_AS_PLCY' => "Educational Policy and Leadership Studies - School Curriculum and Assessment Policy",
    'EDUC_PLS:SP_SOC_FDTN_ED' => "Educational Policy and Leadership Studies - Schools, Culture and Society",
    'ELEC_COMP_ENGR:SP_SFTWR_ENGR_(ECE)' => "Electrical and Computer Engineering - Software Engineering",
    'ELEC_COMP_ENGR' => "Electrical and Computer Engineering",
    'ELEM_EDUC' => "Elementary Education",
    'EMER_INFEC_DIS' => "Emerging Infectious Disease Epidemiology",
    'ENGIN_INFO_TECH:SP_INFO_TECH' => "Engineering and Information Technology - Information Technology",
    'ENGIN_INFO_TECH:SP_MECH_ENG' => "Engineering and Information Technology - Mechanical Engineering",
    'ENGL:SP_CREAT_WRT' => "English - Creative Writing",
    'ENGL:SP_LIT_ST' => "English - Literary Studies",
    'ENGL:SP_NONFIC' => "English - Nonfiction Writing",
    'ENGL' => "English",
    'EPID' => "Epidemiology",
    'FAM_NURSE_PRACT' => "Family Nurse Practitioner",
    'FILM_STDS' => "Film Studies",
    'FILM_VIDEO' => "Film and Video Production",
    'FINANCE' => "Finance",
    'FREE_RADIC_RAD' => "Free Radical and Radiation Biology",
    'FREN_FRANC' => "French and Francophone World Studies",
    'GENETICS:SP_COMP_GENET' => "Genetics - Computational Genetics",
    'GENETICS' => "Genetics",
    'GEOG' => "Geography",
    'GEOS' => "Geoscience",
    'GERMAN' => "German",
    'GLOB_HLTH' => "Global Health Studies",
    'GREEK' => "Greek",
    'HEALTH_POLICY' => "Health Policy",
    'HEALTH_SYSTEMS' => "Health Systems",
    'HIST' => "History",
    'HLTHCARE_MGMT' => "Healthcare Management",
    'HLTH_HUM_PHYS:SP_CHILD_LIFE_HHP' => "Health and Human Physiology - Child Life",
    'HLTH_HUM_PHYS:SP_CLIN_EXER_PHYS' => "Health and Human Physiology - Clinical Exercise Physiology",
    'HLTH_HUM_PHYS' => "Health and Human Physiology",
    'HLTH_MGMT_POL:SP_BUSINESS' => "Health Management and Policy - Business",
    'HLTH_MGMT_POL:SP_EXECUTIVE' => "Health Management and Policy - Executive",
    'HLTH_MGMT_POL:SP_LW' => "Health Management and Policy - Law",
    'HLTH_MGMT_POL' => "Health Management and Policy",
    'HLTH_SVC_POL' => "Health Services and Policy",
    'HUMAN_TOX' => "Human Toxicology",
    'IMMUN' => "Immunology",
    'IND_ENGR' => "Industrial Engineering",
    'INFORM:SP_BIOINF_CMP' => "Informatics - Bioinformatics and Computational Biology",
    'INFORM:SP_GEOINFORMATICS' => "Informatics - Geoinformatics",
    'INFORM:SP_HLTH_INFORM' => "Informatics - Health Informatics",
    'INFORM:SP_HLTH_INFO_PHARM' => "Informatics - Health Informatics-Pharmacy",
    'INFORM:SP_INFO_SCI_(INFO)' => "Informatics - Information Science",
    'INFORM' => "Informatics",
    'INST_RES_EFFECT' => "Institutional Research and Effectiveness",
    'INTEGRATED_BIOLOGY' => "Integrated Biology",
    'INTERDISC_STUDIES:SP_INT_ST_SELF-DEFINED' => "Interdisciplinary Studies - Self-Defined",
    'JRNL' => "Journalism",
    'LATIN' => "Latin",
    'LIBR_INFO_SCI' => "Library and Information Science",
    'LING' => "Linguistics",
    'LIT_TRANS' => "Literary Translation",
    'MASS_COMMS' => "Mass Communications",
    'MASTERS_PH:SP_BIOSTATS_MPH_PRO' => "MPH Program - Biostatistics",
    'MASTERS_PH:SP_COMM_BEH_HLTH_MPH_PG' => "MPH Program - Community and Behavioral Health",
    'MASTERS_PH:SP_EPIDEM_MPH_PG' => "MPH Program - Epidemiology",
    'MASTERS_PH:SP_ERGON_MPH_PG' => "MPH Program - Ergonomics",
    'MASTERS_PH:SP_LAW' => "MPH Program - Law",
    'MASTERS_PH:SP_MEDICINE' => "MPH Program - Medicine",
    'MASTERS_PH:SP_OCC_ENV_HLTH_MPH' => "MPH Program - Occupational and Environmental Health",
    'MASTERS_PH:SP_PHARMACY' => "MPH Program - Pharmacy",
    'MASTERS_PH:SP_POL_MPH_PG' => "MPH Program - Policy",
    'MASTERS_PH:SP_PRACT_VETERINARIANS' => "MPH Program - Practicing Veterinarians",
    'MASTERS_PH:SP_VETERINARY_MED' => "MPH Program - Veterinary Medicine",
    'MASTERS_PH' => "MPH Program",
    'MATH' => "Mathematics",
    'MECH_ENGR' => "Mechanical Engineering",
    'MICROBIOL' => "Microbiology",
    'MOL_BIOL' => "Molecular Biology",
    'MOL_CELL_BIOL' => "Molecular and Cellular Biology",
    'MOL_PHYS_BIOPHYS' => "Molecular Physiology and Biophysics",
    'MSTP' => "Medical Scientist Training Program",
    'MUSIC:SP_BRASS' => "Music - Brass",
    'MUSIC:SP_CHOR_CNDCT_PED' => "Music - Choral Conducting & Pedagogy",
    'MUSIC:SP_COMPOSITION' => "Music - Composition",
    'MUSIC:SP_JAZZ_ST' => "Music - Jazz Studies",
    'MUSIC:SP_MUSICOL' => "Music - Musicology",
    'MUSIC:SP_MUSIC_THER' => "Music - Music Therapy",
    'MUSIC:SP_MUS_ED' => "Music - Music Education",
    'MUSIC:SP_MUS_THEORY' => "Music - Music Theory",
    'MUSIC:SP_ORCH_CNDCT' => "Music - Orchestral Conducting",
    'MUSIC:SP_ORGAN' => "Music - Organ",
    'MUSIC:SP_PERCUS' => "Music - Percussion",
    'MUSIC:SP_PIANO' => "Music - Piano",
    'MUSIC:SP_STRING' => "Music - String",
    'MUSIC:SP_VOICE' => "Music - Voice",
    'MUSIC:SP_WIND_CNDCT' => "Music - Wind Conducting",
    'MUSIC:SP_WOODWIND' => "Music - Woodwind",
    'MUSIC' => "Music",
    'MUSIC_SACRED' => "Sacred Music",
    'NEUROSCI' => "Neuroscience",
    'NURS:SP_ADULT/GER_NP' => "Nursing - Adult Gerontology Primary Care Nurse Practitioner",
    'NURS:SP_ADULT_GER_NP_ACUTE' => "Nursing - Adult Gerontology Acute Care Nurse Practitioner",
    'NURS:SP_ANES_NURS' => "Nursing - Anesthesia Nursing",
    'NURS:SP_CLIN_NURS_LD' => "Nursing - Clinical Nurse Leader",
    'NURS:SP_FAMILY_NP' => "Nursing - Family Nurse Practitioner",
    'NURS:SP_HEALTH_SYSTEMS' => "Nursing - Health Systems",
    'NURS:SP_NURS_INFOR' => "Nursing - Nursing Informatics",
    'NURS:SP_NURS_MGR' => "Nursing - Nurse Manager",
    'NURS:SP_PED_NP' => "Nursing - Pediatric Nurse Practitioner",
    'NURS:SP_PED_NP_ACUTE' => "Nursing - Pediatric Nurse Practitioner-Acute Care",
    'NURS:SP_PED_NP_PC' => "Nursing - Pediatric Nurse Practitioner-Primary Care",
    'NURS:SP_PSYCH_MH_APN' => "Nursing - Psychiatric/Mental Health Nurse Practitioner",
    'NURS' => "Nursing",
    'OCC_ENV_HLTH:SP_AG_SAF_HLTH' => "Occupational and Environmental Health - Agricultural Safety & Health",
    'OCC_ENV_HLTH:SP_INDUS_HYG' => "Occupational and Environmental Health - Industrial Hygiene",
    'OCC_ENV_HLTH' => "Occupational and Environmental Health",
    'ONLINE_TEACHING' => "Online Teaching",
    'ORAL_MAX_SURG' => "Oral and Maxillofacial Surgery",
    'ORAL_SCI' => "Oral Science",
    'ORTHODONTICS' => "Orthodontics",
    'PATHOLOGY' => "Pathology",
    'PED_NRSE_PRACT_ACUTE_CARE' => "Pediatric Nurse Practitioner-Acute Care",
    'PED_NRSE_PRACT_PRI_CARE' => "Pediatric Nurse Practitioner-Primary Care",
    'PHAR:SP_CLIN_PHRM_SCI' => "Pharmacy - Clinical Pharmaceutical Sciences",
    'PHAR:SP_MED_NAT_PROD_CHEM' => "Pharmacy - Medicinal & Natural Products Chemistry",
    'PHAR:SP_PHARM' => "Pharmacy - Pharmaceutics",
    'PHAR:SP_PHARM_SOCIOECON' => "Pharmacy - Health Services Research",
    'PHAR' => "Pharmacy",
    'PHARMC' => "Pharmacology",
    'PHIL' => "Philosophy",
    'PHYSICS:SP_ASTRONOMY' => "Physics - Astronomy",
    'PHYSICS' => "Physics",
    'PHYS_REH_SCI' => "Physical Rehabilitation Science",
    'PHYS_THER' => "Physical Therapy",
    'PH_CERT_GRAD' => "Public Health",
    'POL_SCI' => "Political Science",
    'PSYCH:SP_ANIMAL_LRN_PSYCH' => "Psychology - Animal Learning and Biopsychology",
    'PSYCH:SP_CHLD_DEV_PSYCH' => "Psychology - Child Development and Psychology",
    'PSYCH:SP_CLIN_DEV_PSYCH' => "Psychology - Clinical-Developmental Psychology",
    'PSYCH:SP_CLIN_PSYCH' => "Psychology - Clinical Psychology",
    'PSYCH:SP_GEN_EXP_PSYCH' => "Psychology - General Experimental Psychology",
    'PSYCH:SP_SOC_PSYCH' => "Psychology - Social Psychology",
    'PSYCH' => "Psychology",
    'PSYCH_MNTL_HLTH_NRS_PRAC' => "Psychiatric/Mental Health Nurse Practitioner",
    'PSYCH_QUANT:SP_COUPLE_FAM_THER' => "Psychological and Quantitative Foundations - Couple and Family Therapy",
    'PSYCH_QUANT:SP_C_PSYCH' => "Psychological and Quantitative Foundations - Counseling Psychology",
    'PSYCH_QUANT:SP_EDUC_PSYCH' => "Psychological and Quantitative Foundations - Educational Psychology",
    'PSYCH_QUANT:SP_ED_MEAS_STAT' => "Psychological and Quantitative Foundations - Educational Measurement and Statistics",
    'PSYCH_QUANT:SP_LRNG_SCI' => "Psychological and Quantitative Foundations - Learning Sciences",
    'PSYCH_QUANT:SP_SCHL_PSYCH' => "Psychological and Quantitative Foundations - School Psychology",
    'PSYCH_QUANT' => "Psychological and Quantitative Foundations",
    'PUB_AFF' => "Public Affairs",
    'RELIG_STDS' => "Religious Studies",
    'SCI_EDUC' => "Science Education",
    'SEC_EDUC' => "Secondary Education",
    'SEC_LANG_ACQ' => "Second Language Acquisition",
    'SOCIOL' => "Sociology",
    'SOC_WK:SP_SOC_WORK_ADV_ST' => "Social Work - Advanced Standing",
    'SOC_WK:SP_SW_ACC_ADV_ST' => "Social Work - Accelerated Advanced Standing",
    'SOC_WK' => "Social Work",
    'SPAN' => "Spanish",
    'SPAN_CRTV_WRTG' => "Spanish Creative Writing",
    'SPEC_COLL_LIBRNSHP' => "Special Collections Librarianship",
    'SPEC_EDUC' => "Special Education",
    'SPEECH_HEAR_SCI' => "Speech and Hearing Science",
    'SPEECH_PATH_AUD' => "Speech Pathology and Audiology",
    'SPORT_REC_MGMT' => "Sport and Recreation Management",
    'STAT:SP_ACT_SCI' => "Statistics - Actuarial Science",
    'STAT' => "Statistics",
    'STOMA:SP_ORAL_MAX_RAD' => "Stomatology - Oral and Maxillofacial Radiology",
    'STOMA:SP_ORAL_MED' => "Stomatology - Oral Medicine",
    'STOMA:SP_ORAL_PATH' => "Stomatology - Oral Pathology",
    'STOMA' => "Stomatology",
    'STRATEGIC_COMM' => "Strategic Communication",
    'SUSTAIN_WATER_DEV' => "Sustainable Water Development",
    'TCH_LRN:SP_ART_ED' => "Teaching and Learning - Art Education",
    'TCH_LRN:SP_DEV_READ' => "Teaching and Learning - Developmental Reading",
    'TCH_LRN:SP_ENGL_ED' => "Teaching and Learning - English Education",
    'TCH_LRN:SP_FGN_LANG_ESL_ED' => "Teaching and Learning - Multilingual Education",
    'TCH_LRN:SP_LANG_LIT_CLTR_GLBL_ED' => "Teaching and Learning - Literacy, Culture, and Language Education",
    'TCH_LRN:SP_MATH_ED' => "Teaching and Learning - Mathematics Education",
    'TCH_LRN:SP_SCI_ED' => "Teaching and Learning - Science Education",
    'TCH_LRN:SP_SPEC_ED' => "Teaching and Learning - Special Education",
    'TCH_LRN:SP_SS_ED' => "Teaching and Learning - Social Studies Education",
    'TCH_LRN:SP_STEM_EDUC' => "Teaching and Learning - STEM Education",
    'TCH_LRN:SP_TCHNG_LDRSHP_CLT_COMP' => "Teaching and Learning - Teaching, Leadership, and Cultural Competency",
    'TCH_LRN:SP_WORLD_LANG_ED' => "Teaching and Learning - World Language Education",
    'THEATRE_ARTS:SP_ACTING' => "Theatre Arts - Acting",
    'THEATRE_ARTS:SP_COST_DIR' => "Theatre Arts - Costume Direction",
    'THEATRE_ARTS:SP_DESIGN' => "Theatre Arts - Design",
    'THEATRE_ARTS:SP_DIRECTING' => "Theatre Arts - Directing",
    'THEATRE_ARTS:SP_DRAMA' => "Theatre Arts - Dramaturgy",
    'THEATRE_ARTS:SP_PLAYWRT' => "Theatre Arts - Playwriting",
    'THEATRE_ARTS:SP_STAGE_MGMT' => "Theatre Arts - Stage Management",
    'THEATRE_ARTS' => "Theatre Arts",
    'TRANSL_BIOMED' => "Translational Biomedicine",
    'TRANSL_CLIN_INVEST' => "Translational and Clinical Investigation",
    'TRANSP_STDS' => "Transportation Studies",
    'URBAN_REG' => "Urban and Regional Planning",
    'WM_STDS' => "Gender, Women's and Sexuality Studies",
  ];
}

/**
 * Implements hook_allowed_values_function().
 */
function srop_year_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  // Available srop year values.
  $thisyear = date('Y');
  $i = 2000;
  $options = [];
  while ($i <= $thisyear) :
    $options[$i] = $i;
    $i++;
  endwhile;
  return $options;
}
