<?php

/**
 * @file
 * Primary module hooks for Dentistry Core module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 */
function dentistry_core_page_attachments(array &$attachments) {
  /** @var \Drupal\Core\Path\PathMatcherInterface $path_matcher */
  $path_matcher = \Drupal::service('path.matcher');

  if ($path_matcher->isFrontPage()) {
    /** @var \Drupal\schema_metatag\SchemaMetatagManagerInterface $mtm */
    $mtm = \Drupal::service('schema_metatag.schema_metatag_manager');

    $dentist = [
      'foo' => 'bar',
    ];

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => $mtm->encodeJsonLd($dentist),
        '#attributes' => [
          'type' => 'application/ld+json',
        ],
      ],
      'dentistry_core_dentist',
    ];

    $edu = [
      'baz' => 'qux',
    ];

    $attachments['#attached']['html_head'][] = [
      [
        '#type' => 'html_tag',
        '#tag' => 'script',
        '#value' => $mtm->encodeJsonLd($edu),
        '#attributes' => [
          'type' => 'application/ld+json',
        ],
      ],
      'dentistry_core_edu',
    ];
  }
}
