project:
  machine_name: labscar
  human_name: scar.lab.uiowa.edu
  local:
    hostname: labscar.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: labscar.prod
drupal:
  db:
    database: scar_lab_uiowa_edu
uiowa:
  requester: jbigalke
  site-name: SCAR.lab.uiowa.edu
