<?php

/**
 * @file
 * Primary module hooks for SiteNow People module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 */
function sitenow_people_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'person':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . " " . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}

/**
 * Alter the fields used to represent an entity in the IEF table.
 *
 * @param array $fields
 *   The fields, keyed by field name.
 * @param array $context
 *   An array with the following keys:
 *   - parent_entity_type: The type of the parent entity.
 *   - parent_bundle: The bundle of the parent entity.
 *   - field_name: The name of the reference field on which IEF is operating.
 *   - entity_type: The type of the referenced entities.
 *   - allowed_bundles: Bundles allowed on the reference field.
 *
 * @see \Drupal\inline_entity_form\InlineFormInterface::getTableFields()
 */
function sitenow_people_inline_entity_form_table_fields_alter(array &$fields, array $context) {
  if ($context['entity_type'] == 'node') {
    if (in_array('person', $context['allowed_bundles'])) {
      unset($fields['label']);
      unset($fields['status']);
      $fields['field_person_first_name'] = [
        'type' => 'field',
        'label' => t('First Name'),
        'weight' => 0,
      ];
      $fields['field_person_last_name'] = [
        'type' => 'field',
        'label' => t('Last Name'),
        'weight' => 1,
      ];
      $fields['moderation_state'] = [
        'type' => 'field',
        'label' => t('State'),
        'weight' => 2,
      ];
    }
  }
}
