<?php

/**
 * @file
 * Primary module hooks for brand_core module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function brand_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_lockup_edit_form':
    case 'node_lockup_form':
      // Attach lockup preview libraries.
      $form['#attached']['library'][] = 'brand_core/lockup-preview';

      // Pass relative module path for use in custom template.
      $module_handler = Drupal::service('module_handler');
      $form["#module_path"] = $module_handler->getModule('brand_core')->getPath();

      // Add hidden field for validation.
      $form['is_valid'] = array(
        '#type' => 'hidden',
        '#value' => '0',
        '#attributes' => array(
          'id' => array(
            'is-input-valid',
          ),
        ),
      );

      break;
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function brand_core_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  // Suggest a template with placeholder lockup preview markup.
  if (isset($variables['form'])) {
    if ($variables["form"]["#form_id"] == 'node_lockup_form' || $variables['form']['#form_id'] == 'node_lockup_edit_form') {
      $suggestions[] = 'node_edit_form__lockup';
    }
  }
}

/**
 * Implements hook_theme().
 */
function brand_core_theme($existing, $type, $theme, $path) {
  return [
    'node_edit_form__lockup' => [
      'template' => 'node-edit-form--lockup',
      'base hook' => 'form',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function brand_core_mail($key, &$message, $params) {
  $message['from'] = \Drupal::config('system.site')->get('mail');
  $options = [
    'langcode' => $message['langcode'],
  ];
  switch ($key) {
    case 'lockup-review-digest':
      $message['subject'] = t('Brand Manual - You have @results @label to review', ['@results' => $params['results'], '@label' => $params['label']], $options);
      $message['body'][] = t('You have @results @label to review:', [
        '@results' => $params['results'],
        '@label' => $params['label'],
        '@login' => $params['login'],
      ], $options);
      foreach ($params['lockups'] as $lockup) {
        $message['body'][] = t('- @lockup', ['@lockup' => $lockup], $options);
      }
      $message['body'][] = t('@login', ['@login' => $params['login']], $options);
      break;
  }
}
