<?php

/**
 * @file
 * Contains uiowa_lb_blocks.module.
 */

use Drupal\block\Entity\Block;

/**
 * Implements hook_form_alter().
 */
function uiowa_lb_blocks_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'layout_builder_add_block') {
    $form['layout_builder_block_override'] = [
      '#type' => 'checkbox',
      '#title' => t("Override Block Styles"),
      '#required' => FALSE,
    ];
    $form['layout_builder_style_margin']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
  }
  if ($form_id == 'layout_builder_update_block') {
    $form['layout_builder_block_override'] = [
      '#type' => 'checkbox',
      '#title' => t("Override Block Styles"),
      '#required' => FALSE,
    ];
    $form['layout_builder_style_margin']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_html().
 */
function uiowa_lb_blocks_preprocess_html(&$variables) {
  $block_breadcrumbs = Block::load('collegiate_theme_page_title');
  if (isset($block_breadcrumbs)) {
    $visibility = $block_breadcrumbs->getVisibility();
    $visibility['entity_bundle:node']['bundles']['article'] = 'article';
    $visibility['entity_bundle:node']['bundles']['page'] = 'page';
    $visibility['entity_bundle:node']['negate'] = 1;
    $block_breadcrumbs->setVisibilityConfig('entity_bundle:node', $visibility['entity_bundle:node']);
    $block_breadcrumbs->save();
  }

  $block_title = Block::load('collegiate_theme_breadcrumbs');
  if (isset($block_title)) {
    $visibility = $block_title->getVisibility();
    $visibility['entity_bundle:node']['bundles']['article'] = 'article';
    $visibility['entity_bundle:node']['bundles']['page'] = 'page';
    $visibility['entity_bundle:node']['negate'] = 1;
    $block_title->setVisibilityConfig('entity_bundle:node', $visibility['entity_bundle:node']);
    $block_title->save();
  }
}
