<?php

/**
 * @file
 * Contains uiowa_lb_blocks.module.
 */

/**
 * Implements hook_form_alter().
 */
function uiowa_lb_blocks_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'layout_builder_add_block') {
    $form['layout_builder_block_override'] = [
      '#type' => 'checkbox',
      '#title' => t("Override Block Styles"),
      '#required' => FALSE,
    ];
    $form['layout_builder_style_margin']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
    $form['layout_builder_style_heading']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
     $form['layout_builder_style']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
  }
  if ($form_id == 'layout_builder_update_block') {
    $form['layout_builder_block_override'] = [
      '#type' => 'checkbox',
      '#title' => t("Override Block Styles"),
      '#required' => FALSE,
    ];
    $form['layout_builder_style_margin']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
    $form['layout_builder_style_heading']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
    $form['layout_builder_style']['#states'] = [
      'visible' => [
        ':input[name="layout_builder_block_override"]' => [
          'checked' => TRUE,
        ],
      ],
    ];
  }
}
