<?php

/**
 * @file
 * Contains uiowa_lb_blocks.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function uiowa_lb_blocks_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'layout_builder_add_block') {
    $form['layout_builder_block_override'] = array(
      '#type' => 'checkbox',
      '#title' => t("Override this block's default margins."),
      '#required' => FALSE,
    );
    $form['layout_builder_style_margin']['#states'] = [
    'visible' => [
      ':input[name="layout_builder_block_override"]' => [
        'checked' => TRUE,
      ],
    ],
    ];
  }
  if ($form_id == 'layout_builder_update_block') {
    $form['layout_builder_block_override'] = array(
      '#type' => 'checkbox',
      '#title' => t("Override this block's default margins."),
      '#required' => FALSE,
    );
    $form['layout_builder_style_margin']['#states'] = [
    'visible' => [
      ':input[name="layout_builder_block_override"]' => [
        'checked' => TRUE,
      ],
    ],
    ];
  }
}
