<?php

/**
 * @file
 * Primary module hooks for sitenow_carousel module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Template\Attribute;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;

/**
 * Implements hook_preprocess_field().
 */
function sitenow_carousel_preprocess_field(&$variables) {
  /** @var Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');

  switch ($variables['element']['#field_name']) {
    case 'field_carousel_item':

      if (!$admin_context->isAdminRoute()) {
        $variables['attributes']['class'][] = 'carousel-inner';
      }

      break;
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function sitenow_carousel_preprocess_paragraph__carousel(&$variables) {
  /** @var Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  /** @var Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');

  if (!$admin_context->isAdminRoute()) {
    $variables['id'] = 'carousel-' . $paragraph->id();

    if (isset($variables['content']['field_carousel_item'][0])) {
      $variables['content']['field_carousel_item'][0]['#attributes'] = new Attribute();
      $variables['content']['field_carousel_item'][0]['#attributes']->addClass('active');
    }

    // Subtract one from the number of items since the indicators are zero-based.
    // @see paragraph--carousel--default.html.twig
    $variables['carousel_item_count'] = $variables['content']['field_carousel_item']['#items']->count() - 1;
  }
}

/**
 * Implements hook_preprocess_paragraph().
 */
function sitenow_carousel_preprocess_paragraph__carousel_item(&$variables) {
  /** @var Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['paragraph'];

  /** @var Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');

  if (!$admin_context->isAdminRoute()) {
    $image_field = $paragraph->get('field_carousel_item_image');

    if (!$image_field->isEmpty()) {
      $image = $image_field->first()->getValue();
      $media = Media::load($image['target_id']);
      $media_field = $media->get('field_media_image')
        ->first()
        ->getValue();

      $file = File::load($media_field['target_id']);
      $uri = $file->getFileUri();
      $alt = ($media_field['alt'] ? $media_field['alt'] : '');

      $image = [
        '#theme' => 'image_style',
        '#width' => NULL,
        '#height' => NULL,
        '#style_name' => 'sitenow_carousel',
        '#uri' => $uri,
        '#alt' => $alt,
        '#weight' => -1,
        '#attributes' => [
          'class' => [
            'd-block',
            'w-100',
          ],
        ],
      ];

      $variables['content']['carousel_item_preprocessed_image'] = $image;
    }
  }
}
