<?php

/**
 * @file
 * Contains grad_core.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\grad_core\Entity\GradScholar;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function grad_core_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['scholar'])) {
    $bundles['node']['scholar']['class'] = GradScholar::class;
  }
}

/**
 * Implements hook_entity_presave().
 */
function grad_core_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'scholar':
      // Setting the title with the first/last name values.
      $output = $entity->get('field_person_first_name')->value . " " . $entity->get('field_person_last_name')->value;
      $entity->setTitle($output);
      break;

  }
}

/**
 * Implements hook_form_alter().
 */
function grad_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_scholar_edit_form':
    case 'node_scholar_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_core_preprocess_block(&$variables) {
  switch ($variables['plugin_id']) {
    case 'field_block:node:student_profile:field_grad_program_all_degree':
      uiowa_core_set_attributes($variables, [
        'block-margin__top',
      ]);
      break;

  }
}

/**
 * Implements hook_preprocess_field().
 */
function grad_core_preprocess_field(&$variables, $hook) {
  switch ($variables['element']['#field_name']) {
    case 'field_uiowa_college':
      uiowa_core_set_field_icon($variables, 'fas fa-university');

      break;

  }
}
