<?php

/**
 * @file
 * Primary module hooks for sitenow_core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 */
function sitenow_core_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (isset($element['#webform_id']) && $element['#webform_id'] === 'request_a_site--url') {
    $element['#element_validate'][] = [
      'Drupal\sitenow_core\Validate\RequestASiteUrlConstraint',
      'validate',
    ];
  }
}
