<?php

/**
 * @file
 * Primary module hooks for sitenow_core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_element_alter().
 */
function sitenow_core_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  if (isset($element['#webform_id']) && $element['#webform_id'] === 'request_a_site--uri') {
    $element['#element_validate'][] = [
      'Drupal\sitenow_core\Validate\RequestASiteUriConstraint',
      'validate',
    ];
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function sitenow_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'block_view_alter'
    && isset($implementations['sitenow_core'], $implementations['uiowa_auth'])) {
    $group = $implementations['sitenow_core'];
    unset($implementations['sitenow_core']);
    $implementations['sitenow_core'] = $group;
  }
}
