<?php

/**
 * @file
 * Module code for SiteNow Signage.
 */

use Drupal\Core\Render\Element;
use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_node().
 */
function sitenow_signage_preprocess_node(&$variables) {
  if ($variables['node']->getType() == 'slide') {
    $variables['label'] = NULL;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_signage_preprocess_page(&$variables) {
  // Check if the current page is a node of type 'sign'.
  if (isset($variables['node']) && $variables['node'] instanceof NodeInterface && $variables['node']->getType() === 'sign') {
    // Remove regions.
    $variables['page']['header'] = [];
    $variables['page']['after_content'] = [];
    $variables['page']['pre_footer'] = [];
    $variables['page']['footer_first'] = [];
    $variables['page']['footer_second'] = [];
    // Check that user is logged out before unsetting anything.
    if (\Drupal::currentUser()->isAnonymous()) {
      // Check if the query string contains the 'signage-display' parameter.
      if (isset(\Drupal::request()?->query?->all()['signage-display'])) {
        // Remove all the regions from the page.
        foreach (Element::children($variables['page']) as $key) {
          if ($key !== 'content') {
            unset($variables['page'][$key]);
          }
        }
        // Add a cache context so that the page is cached separately.
        $variables['#cache']['contexts'][] = 'url.query_args:signage-display';
      }
    }

  }
}
