project:
  machine_name: labalt
  human_name: alt.lab.uiowa.edu
  local:
    hostname: labalt.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: labalt.prod
drupal:
  db:
    database: alt_lab_uiowa_edu
uiowa:
  requester: bwalizer
  site-name: 'Advanced Learning Traces (ALT) Lab'
