<?php

/**
 * @file
 * Primary module hooks for UIowa Profiles module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function uiowa_profiles_preprocess_page(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();

  if ($route == 'uiowa_profiles.directory') {
    unset($variables['page']['breadcrumb']);
  }
}
