<?php

/**
 * @file
 * Hooks for UIowa Profiles module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function uiowa_profiles_preprocess_page(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();

  if (strpos($route, 'uiowa_profiles.directory') === 0) {
    // We know it is a directory instance, and we want to remove the original
    // breadcrumbs so the app can handle them.
    unset($variables['page']['breadcrumb']);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function uiowa_profiles_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();

  if (strpos($route, 'uiowa_profiles.directory') === 0) {
    // Let the app set the head title using the slug of the person.
    unset($variables['head_title']);
  }
}
