<?php

/**
 * @file
 * Contains grad_admissions_core.module.
 */

/**
 * Implements hook_theme().
 */
function grad_admissions_core_theme($existing, $type, $theme, $path) {
  return [
    'node__grad_costs_estimate' => [
      'template' => 'node--grad-costs-estimate',
      'base hook' => 'node',
    ],
    'node__area_of_study__full' => [
      'template' => 'node--area-of-study--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_admissions_core_preprocess_field(&$variables) {
  switch ($variables["element"]["#field_name"]) {
    case 'field_area_of_study_grad_intro':
      $variables["label"] = t('Estimated Cost of Attendance');
      break;

  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function grad_admissions_core_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  switch ($variables["element"]["#field_name"]) {
    case 'field_area_of_study_grad_intro':
      $suggestions[] = 'field__bold_headline_label';
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function grad_admissions_core_preprocess_node(&$variables) {

  $node = $variables["node"];
  switch ($node->getType()) {
    case 'area_of_study':
      $variables['#attached']['library'][] = 'uids_base/twocol';
      break;
  }
}
