<?php

/**
 * @file
 * Custom functionality the INRC website.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\inrc_core\Entity\Grant;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function inrc_core_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['grant'])) {
    $bundles['node']['grant']['class'] = Grant::class;
  }
}

/**
 * Implements hook_form_alter().
 */
function inrc_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_grant_form':
    case 'node_grant_edit_form':
      _sitenow_node_form_defaults($form, $form_state);
      // Add our custom submit handler to remove the country code
      // if no other address info is available. Add it to the front
      // of the queue so we don't bother processing it after.
      array_unshift($form['actions']['submit']['#submit'], 'inrc_core_grant_form_submit');
      break;
  }
}

/**
 * Custom submit handler for node grant forms.
 */
function inrc_core_grant_form_submit(array &$form, FormStateInterface $form_state) {
  $contact_address = $form_state->getValue('field_grant_address');
  if (isset($contact_address[0]['address'])) {
    $has_info = FALSE;
    // Loop through all the details of the address to
    // check if any of them have been set besides the
    // country.
    foreach ($contact_address[0]['address'] as $key => $details) {
      if ($key === 'country_code') {
        continue;
      }
      // If we find a non-empty value, we can stop looping.
      if (!empty($details)) {
        $has_info = TRUE;
        break;
      }
    }

    // If no other fields have been set, then unset the address.
    if (!$has_info) {
      // Set country code to empty string.
      $form_state->setValue([
        'field_grant_address',
        0,
        'address',
        'country_code',
      ], '');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function inrc_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-grants-block-grants') {
    $form['#attached']['library'][] = 'uids_base/view-bef';
  }
}
