<?php

/**
 * @file
 * Contains ccom_core.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function ccom_core_preprocess_block(&$variables) {
  if (isset($variables['attributes']['id']) && str_contains($variables['attributes']['id'], 'footercontactinfo')) {
    $current_path = \Drupal::request()->getRequestUri();
    $full_url = \Drupal::request()->server->get('HTTP_HOST') . $current_path;
    $newlink = '<p><a href="http://hc-vbugtracker.healthcare.uiowa.edu/projects/uihc-org/issues/new?issue[custom_field_values][1]=' . $full_url . '">Report an issue with this page</a></p>';
    $variables["content"]["field_uiowa_text_area"][0]['#text'] .= $newlink;
    $variables['#cache'] = [
      'max-age' => 0,
    ];
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function ccom_core_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {

    // Move our hook_page_attachments() implementation to the end of the list,
    // so that we know it will fire after uiowa_core's implementation.
    case 'page_attachments':
      $group = $implementations['ccom_core'];
      unset($implementations['ccom_core']);
      $implementations['ccom_core'] = $group;
      break;

  }
}

/**
 * Implements hook_page_attachments().
 */
function ccom_core_page_attachments(&$page) {
  // Remove the universal GTM container,
  // which is added through the 'uiowa_core/gtag' library attachment.
  $library = $page['#attached']['library'];
  $to_remove = 'uiowa_core/gtag';
  $page['#attached']['library'] = array_values(array_filter($library, fn ($x) => $x != $to_remove));
}
