<?php

/**
 * @file
 * Contains ccom_core.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function ccom_core_preprocess_block(&$variables) {
  if (isset($variables['attributes']['id']) && str_contains($variables['attributes']['id'], 'footercontactinfo')) {
    $current_path = \Drupal::request()->getRequestUri();
    $full_url = \Drupal::request()->server->get('HTTP_HOST') . $current_path;
    $encoded_url = urlencode($full_url);
    $newlink = '<p><a href="https://service.uiowa.edu/portal/service?id=1734&customfield_1489=' . $encoded_url . '&customfield_1487=2">Report an issue with this page</a></p>';
    $variables["content"]["field_uiowa_text_area"][0]['#text'] .= $newlink;
    $variables['#cache'] = [
      'max-age' => 0,
    ];
  }
}