field.storage_settings.heading_config:
  type: mapping
  label: 'Heading configuration settings'

field.field_settings.heading_config:
  type: mapping
  label: 'Heading configuration settings'

field.value.heading_config:
  type: mapping
  label: 'Default value'
  mapping:
    hide_headline:
      type: integer
      label: 'Hide headline'
    headline_style:
      type: string
      label: 'Headline style'
    headline_alignment:
      type: string
      label: 'Headline alignment'
    child_heading_size:
      type: string
      label: 'Child heading size'

field.widget.settings.heading_config_widget:
  type: mapping
  label: 'Heading configuration widget settings'

field.widget.settings.heading_config_simple_widget:
  type: mapping
  label: 'Heading configuration simple widget settings'

field.formatter.settings.heading_advanced_formatter:
  type: mapping
  label: 'Heading advanced formatter settings'
  mapping:
    config_field:
      type: string
      label: 'Configuration field name'
