project:
  machine_name: sitesjoydatta
  human_name: joydatta.sites.uiowa.edu
  local:
    hostname: sitesjoydatta.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: sitesjoydatta.prod
drupal:
  db:
    database: joydatta_sites_uiowa_edu
uiowa:
  requester: jdatta
  site-name: 'Joy Datta'
