<?php

/**
 * @file
 * Primary module hooks for SiteNow Area of Study module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Implements hook_allowed_values_function().
 */
function sitenow_area_of_study_allowed_values_function(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable) {
  // Available degree abbreviations.
  // Can be moved to store in a config file later.
  $options = [
    'AuD' => 'AuD',
    'BA' => 'BA',
    'BAS' => 'BAS',
    'BBA' => 'BBA',
    'BFA' => 'BFA',
    'BM' => 'BM',
    'BS' => 'BS',
    'BSE' => 'BSE',
    'BSN' => 'BSN',
    'DDS' => 'DDS',
    'DNP' => 'DNP',
    'EdD' => 'EdD',
    'JD' => 'JD',
    'LLM' => 'LLM',
    'MA' => 'MA',
    'MAc' => 'MAc',
    'MAT' => 'MAT',
    'MCA' => 'MCA',
    'MCS' => 'MCS',
    'MFA' => 'MFA',
    'MHA' => 'MHA',
    'MPH' => 'MPH',
    'MS' => 'MS',
    'MSL' => 'MSL',
    'PhD' => 'PhD',
    'PHR' => 'PHR',
    'SJD' => 'SJD',
  ];
  return $options;
}
