project:
  machine_name: labersm
  human_name: ersm.lab.uiowa.edu
  local:
    hostname: labersm.uiowa.ddev.site
    protocol: https
drush:
  aliases:
    local: self
    remote: labersm.prod
drupal:
  db:
    database: ersm_lab_uiowa_edu
uiowa:
  requester: mlinderm
  site-name: 'Environmental Remote Sensing and Modeling Lab'
