<?php

/**
 * @file
 * Primary module hooks for IISC Core module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function iisc_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_partner_edit_form':
    case 'node_partner_form':
    case 'node_project_edit_form':
    case 'node_project_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}

/**
 * Implements hook_theme().
 */
function iisc_core_theme($existing, $type, $theme, $path) {
  return [
    // @todo Limit this to the teaser, otherwise it will change
    //   the taxonomy term pages as well. Unsure why including it
    //   as taxonomy_term__colleges_and_departments__teaser was
    //   not working (at least locally for me).
    'taxonomy_term__colleges_and_departments' => [
      'template' => 'taxonomy-term--colleges-and-departments--teaser',
      'base hook' => 'taxonomy_term',
    ],
  ];
}
