<?php

/**
 * @file
 * Primary module hooks for IISC Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\iisc_core\Entity\Partner;
use Drupal\iisc_core\Entity\Project;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function iisc_core_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['project'])) {
    $bundles['node']['project']['class'] = Project::class;
  }
  if (isset($bundles['node']['partner'])) {
    $bundles['node']['partner']['class'] = Partner::class;
  }
}

/**
 * Implements hook_form_alter().
 */
function iisc_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_partner_edit_form':
    case 'node_partner_form':
    case 'node_project_edit_form':
    case 'node_project_form':
      _sitenow_node_form_defaults($form, $form_state);
      break;

  }
}
