<?php

/**
 * @file
 * Contains sitenow_p2lb.module.
 */

use Drupal\Core\Database\Database;

/**
 * Check for nodes which are using paragraphs.
 */
function sitenow_p2lb_paragraph_nodes() {
  $connection = Database::getConnection();
  $query = $connection->select('paragraphs_item_field_data', 'pifd');
  $query->fields('pifd', ['parent_id'])
    ->condition('parent_type', 'node', '=');
  $result = $query->distinct()
    ->execute()
    ->fetchCol();
  // @todo All pages will have default section/body combo currently.
  return $result;
}

/**
 * Convert a node from paragraphs to layout builder.
 */
function sitenow_p2lb_node_p2lb($nid) {
  $node = \Drupal::service('entity_type.manager')
    ->getStorage('node')
    ->load($nid);
  // Get sections from the page.
  $section_ids = sitenow_p2lb_fetch_sections($nid);
  return;
}

/**
 * Fetch all section paragraph ids attached to a node.
 */
function sitenow_p2lb_fetch_section_ids($nid) {
  $connection = Database::getConnection();
  $query = $connection->select('paragraphs_item_field_data', 'pifd');
  $query->fields('pifd', ['id'])
    ->condition('parent_type', 'node', '=')
    ->condition('parent_id', $nid, '=');
  $sections = $query->distinct()
    ->execute()
    ->fetchCol();
  return $sections;
}

/**
 * Load paragraph items.
 */
function sitenow_p2lb_load_paragraphs($pid) {
  $paragraph = \Drupal::service('entity_type.manager')
    ->getStorage('paragraph')
    ->load($pid);
  return;
}

/**
 * Process paragraphs section.
 */
function sitenow_p2lb_process_section($section_id) {
  $connection = Database::getConnection();
  $query = $connection->select('paragraphs_item_field_data', 'pifd');
  $query->fields('pifd', ['id', 'type'])
    ->condition('parent_id', $section_id, '=')
    ->condition('parent_field_name', 'field_section_content_block', '=');
  $pids = $query->execute()->fetchAll();
  $col_widths = [];
  $paragraphs = \Drupal::service('entity_type.manager')
    ->getStorage('paragraph')
    ->loadMultiple($pids);
  foreach ($paragraphs as &$paragraph) {
    $paragraph = $paragraph->toArray();
    $col_widths[] = $paragraph['field_uip_colwidth']['value'];
  }
  // @todo Create an lb section based on col_widths
  return;
}

/**
 * Process individual paragraph.
 */
function sitenow_p2lb_process_paragraph($paragraph) {
  switch ($paragraph['type']) {
    case 'section':
      break;

    case 'text':
      // @todo This needs to be checked/extended/cleaned up
      $block = \Drupal::entityTypeManager()
        ->getStorage('block_content')
        ->create([
          'type' => 'uiowa_text_area',
          'info' => [
            'lang' => 'en',
          ],
          'field_uiowa_text_area' => [
            $paragraph['field_text_body'],
          ],
        ]);

      $block->save();
      break;

    case 'accordion':
    case 'accordion_item':
    case 'blockquote':
    case 'card':
    case 'image_gallery':
    case 'webform':
    case 'featured_content':
    case 'carousel':
    case 'carousel_image':
    default:

  }
  return;
}

/**
 * Removes all attached paragraphs from a node.
 */
function sitenow_p2lb_remove_attached_paragraphs($nid) {
  $section_ids = sitenow_p2lb_fetch_section_ids($nid);
  // Grab paragraphs attached to each of the given sections.
  $connection = Database::getConnection();
  $query = $connection->select('paragraphs_item_field_data', 'pifd');
  $query->fields('pifd', ['id'])
    ->condition('parent_id', $section_ids, 'in')
    ->condition('parent_field_name', 'field_section_content_block', '=');
  $child_ids = $query->execute()->fetchCol();
  $ids = array_merge($child_ids, $section_ids);
  $paragraphs = \Drupal::service('entity_type.manager')
    ->getStorage('paragraph')
    ->loadMultiple($ids);
  foreach ($paragraphs as $paragraph) {
    $paragraph->delete();
  }
}