<?php

/**
 * @file
 * Contains hr_core.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_module_implements_alter().
 */
function hr_core_module_implements_alter(&$implementations, $hook) {
  $hooks_to_order = [
    'form_alter',
  ];

  if (in_array($hook, $hooks_to_order)) {
    $group = $implementations['hr_core'];
    unset($implementations['hr_core']);
    $implementations['hr_core'] = $group;
  }
}

/**
 * Implements hook_form_alter().
 */
function hr_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'node_page_edit_form':
    case 'node_page_form':
      if (isset($form['field_related_content']) && isset($form['node_relations'])) {
        // Set field_related_content to node_reference group.
        $form['field_related_content']['#group'] = 'node_relations';
      }
      break;

  }
  switch ($form_id) {
    case 'node_page_edit_form':
    case 'node_page_form':
    case 'node_article_edit_form':
    case 'node_article_form':
      if (isset($form['field_reference'])) {
        // Set field_reference to node_reference group.
        $form['field_reference']['#group'] = 'node_relations';
      }
      break;
  }
}

/**
 * Implements hook_theme().
 */
function hr_core_theme($existing, $type, $theme, $path) {
  return [
    'block__views_block__units_block_contact_info' => [
      'template' => 'block--views-block--units-block-contact-info',
      'base hook' => 'block',
    ],
    'field__taxonomy_term__name__units__teaser' => [
      'template' => 'field--taxonomy-term--name--units--teaser',
      'base hook' => 'field',
    ],
    'taxonomy_term__units' => [
      'template' => 'taxonomy-term--units',
      'base hook' => 'taxonomy_term',
    ],
  ];
}
