<?php

/**
 * @file
 * Contains sitenow_card.module.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_HOOK().
 */
function sitenow_card_preprocess_paragraph__card(&$variables) {
  $paragraph = $variables['paragraph'];
  $admin_context = \Drupal::service('router.admin_context');
  if (!$admin_context->isAdminRoute()) {
    // Create new card attributers.
    $variables['card_attributes'] = new Attribute();
    // Add css if applicable.
    $variables['#attached']['library'][] = 'uids_base/card';
    // Add card link behavior for links.
    $link_field = $paragraph->get('field_card_link');
    if (!$link_field->isEmpty()) {
      $link = $link_field->first()->getValue();
      $url = Url::fromUri($link['uri'], ['alias' => TRUE])->toString();
      $variables['card_attributes']['data-href'] = $url;
      $variables['card_attributes']['tabindex'] = '0';
      $variables['card_attributes']['role'] = 'link';
      $variables['card_attributes']['aria-label'] = $link['title'];
      $variables['card_attributes']['name'] = $link['title'];
      $variables['card_attributes']['title'] = $link['title'];
    }
  }

  if (isset($variables['content']['field_card_link'], $variables['content']['field_card_link'][0])) {
    $variables['content']['field_card_link'][0]['#options']['attributes']['class'][] = 'card-link';
    $variables['content']['field_card_link'][0]['#options']['attributes']['class'][] = 'js-card-link';
  }
}
