<?php

/**
 * @file
 * Custom functionality the records.fo.uiowa.edu website.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\forecords_core\Entity\Record;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function forecords_core_entity_bundle_info_alter(array &$bundles) {
  if (isset($bundles['node']['record'])) {
    $bundles['node']['record']['class'] = Record::class;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function forecords_core_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form['#id'] === 'views-exposed-form-record-block-record') {
    $form['#attached']['library'][] = 'uids_base/view-bef';

    // Append a link to download all records.
    $form['download'] = [
      '#type' => 'link',
      '#title' => t('Download all records <span><i class="fa-solid fa-cloud-arrow-down"></i></span>'),
      '#url' => Url::fromRoute('forecords_core.records_download'),
      '#weight' => 101,
      '#attributes' => [
        'class' => [
          'bttn',
          'bttn--tertiary',
          'bttn--full',
          'bttn--light-font',
        ],
        'rel' => 'nofollow',
        'data-no-ajax' => 'true',
      ],
    ];
  }
}
