<?php

/**
 * @file
 * Primary module hooks for uiowa_maui module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_HOOK().
 */
function uiowa_maui_preprocess_block(&$variables) {
  if ($variables['elements']['#plugin_id'] === 'uiowa_maui_academic_dates') {
    $variables['attributes']['class'][] = 'list-container list-container--list';
  }
}

/**
 * Implements hook_webform_options_WEBFORM_OPTIONS_ID_alter().
 */
function uiowa_maui_webform_options_maui_sessions_alter(array &$options, array &$element) {
  // Get sessions from MAUI for Webform options. 1 previous, 4 future.
  /** @var Drupal\uiowa_maui\MauiApi $maui */
  $maui = \Drupal::service('uiowa_maui.api');
  foreach ($maui->getSessionsBounded(1, 4) as $session) {
    $options[$session->id] = Html::escape($session->shortDescription);
  }

}
