<?php

/**
 * @file
 * Primary module hooks for uiowa_maui module.
 */

use Drupal\layout_builder_custom\HeadlineHelper;

/**
 * Implements hook_theme().
 */
function uiowa_maui_theme($existing, $type, $theme, $path) {
  return [
    'uiowa_maui_session_dates' => [
      'variables' => [
        'headline' => NULL,
        'hide_headline' => NULL,
        'heading_size' => NULL,
        'headline_style' => NULL,
        'child_heading_size' => NULL,
        'data' => NULL,
      ],
    ],
  ];
}

/**
 * Theme preprocess function for uiowa_maui_session_dates.
 */
function template_preprocess_uiowa_maui_session_dates(&$variables) {
  $dates = [];

  foreach ($variables['data'] as $date) {
    $start = strtotime($date->beginDate);
    $end = strtotime($date->endDate);
    $key = $start . $end;

    // The subsession takes priority if set.
    $item = (object) [
      'description' => $date->dateLookup->description,
      'session' => $date->subSession ?? $date->session->shortDescription,
    ];

    // Group items by date.
    if (isset($dates[$key])) {
      $dates[$key]['items'][] = $item;
    }
    else {
      $dates[$key] = [
        'start' => date('F j, Y', $start),
        'end' => date('F j, Y', $end),
        'items' => [$item],
      ];
    }
  }

  $variables['dates'] = $dates;

  // Remove raw data availability in template.
  unset($variables['data']);

  // Rewrite headline classes.
  $style = HeadlineHelper::getStyles()[$variables['headline_style']];
  $variables['headline_class'] = $style;
}
