<?php

/**
 * @file
 * Install hooks for uiowa_events.
 */

/**
 * Implements hook_uninstall().
 */
function uiowa_events_uninstall() {
  // Remove the module configuration.
  \Drupal::configFactory()->getEditable('uiowa_events.settings')->delete();
}

/**
 * Delete the unused uievents database table.
 */
function uiowa_events_update_8001() {
  Drupal::database()->schema()->dropTable('uievents');
  drupal_flush_all_caches();
}
