<?php

/**
 * @file
 * Module code for uiowa seo.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_seo_form_google_analytics_admin_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Restrict access to some Google Analytics form items for all roles
  // except administrator.
  if (!sitenow_is_user_admin(\Drupal::currentUser())) {
    $form['tracking']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
  }
}

/**
 * Implements hook_metatags_alter().
 */
function sitenow_seo_metatags_alter(array &$metatags, array &$context) {
  // Append the page number to the title, if it is set and greater than 0.
  $page = \Drupal::service('pager.parameters')->findPage();

  if ($page) {
    $metatags['title'] .= " | Page {$page}";
  }
}

/**
 * Implements hook_form_alter().
 */
function sitenow_seo_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    // Node form modifications.
    case 'node_page_edit_form':
    case 'node_page_form':
    case 'node_article_edit_form':
    case 'node_article_form':
    case 'node_person_edit_form':
    case 'node_person_form':
      // Collapse inner SEO field groups.
      if (isset($form["field_meta_tags"])) {
        if ($form["field_meta_tags"]["widget"][0]["advanced"]) {
          $form["field_meta_tags"]["widget"][0]["advanced"]["#open"] = FALSE;
        }
        if (isset($form["field_meta_tags"]["widget"][0]["open_graph"])) {
          $form["field_meta_tags"]["widget"][0]["open_graph"]["#open"] = FALSE;
        }
        if (isset($form["field_meta_tags"]["widget"][0]["twitter_cards"])) {
          $form["field_meta_tags"]["widget"][0]["twitter_cards"]["#open"] = FALSE;
        }
      }
      break;

  }
}
