<?php

/**
 * @file
 * Module code for uiowa seo.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sitenow_seo_form_google_analytics_admin_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Restrict access to some Google Analytics form items for all roles
  // except administrator.
  $roles = \Drupal::currentUser()->getRoles();
  if (!in_array('administrator', $roles)) {
    $form['tracking']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
  }
}
