<?php

/**
 * @file
 * Module code for uiowa seo.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uiowa_seo_form_google_analytics_admin_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Restrict access to some Google Analytics form items for all roles
  // except administrator.
  $user = \Drupal::currentUser()->getRoles();
  if (!in_array("administrator", $user)) {
    $form['tracking']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function uiowa_seo_entity_type_alter(array &$entity_types) {
  // Add custom list builder handler to control output for non administrators.
  $entity_types['metatag_defaults']->setHandlerClass('list_builder', '\Drupal\uiowa_seo\CustomListBuilderHandler\CustomListBuilderHandler');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uiowa_seo_form_metatag_defaults_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Restrict access to most meta tag form items for all roles
  // except administrator.
  $user = \Drupal::currentUser()->getRoles();
  if (!in_array("administrator", $user)) {
    $form['basic']['#access'] = FALSE;
    $form['advanced']['#access'] = FALSE;
    $form['schema_article']['#access'] = FALSE;
    $form['schema_web_site']['#access'] = FALSE;
    $form['site_verification']['baidu']['#access'] = FALSE;
    $form['site_verification']['norton_safe_web']['#access'] = FALSE;
    $form['site_verification']['pinterest']['#access'] = FALSE;
    $form['site_verification']['yandex']['#access'] = FALSE;
  }
}
